const todasLasMaterias = [
    // ==========================================
    // CARRERA: ING. EN REDES Y TELECOMUNICACIONES
    // ==========================================
    { id: 'MAT-0125', sem: 1, nom: 'Estructuras Discretas', pre: [], carrera: 'REDES' },
    { id: 'INV-0100', sem: 1, nom: 'Técnicas de Investigación', pre: [], carrera: 'REDES' },
    { id: 'MAT-0100', sem: 1, nom: 'Fundamentos de Matemáticas', pre: [], carrera: 'REDES' },
    { id: 'LIN-0200', sem: 1, nom: 'Inglés I', pre: [], carrera: 'REDES' },
    { id: 'SIS-0120', sem: 1, nom: 'Programación Básica', pre: [], carrera: 'REDES' },
    { id: 'ELC-0100', sem: 1, nom: 'Hardware y Software', pre: [], carrera: 'REDES' },

    { id: 'ELC-0110', sem: 2, nom: 'Sistemas Digitales I', pre: ['MAT-0125'], carrera: 'REDES' },
    { id: 'MAT-0110', sem: 2, nom: 'Álgebra Lineal', pre: ['MAT-0100'], carrera: 'REDES' },
    { id: 'FIS-0100', sem: 2, nom: 'Física I', pre: ['MAT-0100'], carrera: 'REDES' },
    { id: 'LIN-0201', sem: 2, nom: 'Inglés II', pre: ['LIN-0200'], carrera: 'REDES' },
    { id: 'SIS-0200', sem: 2, nom: 'Sistemas Operativos I', pre: ['SIS-0120'], carrera: 'REDES' },
    { id: 'SIS-0121', sem: 2, nom: 'Programación I', pre: ['SIS-0120'], carrera: 'REDES' },

    { id: 'ELC-0120', sem: 3, nom: 'Sistemas Digitales II', pre: ['ELC-0110'], carrera: 'REDES' },
    { id: 'MAT-0120', sem: 3, nom: 'Cálculo I', pre: ['MAT-0100'], carrera: 'REDES' },
    { id: 'FIS-0200', sem: 3, nom: 'Física II', pre: ['FIS-0100'], carrera: 'REDES' },
    { id: 'LIN-0110', sem: 3, nom: 'Deontología y Prosocialidad', pre: [], carrera: 'REDES' },
    { id: 'SIS-0210', sem: 3, nom: 'Taller de Sistemas Operativos I', pre: ['SIS-0200'], carrera: 'REDES' },
    { id: 'SIS-0122', sem: 3, nom: 'Programación II', pre: ['SIS-0121'], carrera: 'REDES' },

    { id: 'ELC-0200', sem: 4, nom: 'Circuitos Eléctricos I', pre: ['ELC-0120'], carrera: 'REDES' },
    { id: 'RED-0100', sem: 4, nom: 'Redes I', pre: ['ELC-0110'], carrera: 'REDES' },
    { id: 'TEL-0100', sem: 4, nom: 'Campos Electromagnéticos', pre: ['FIS-0200'], carrera: 'REDES' },
    { id: 'TEL-0200', sem: 4, nom: 'Análisis de Sistemas y Señales', pre: ['FIS-0200'], carrera: 'REDES' },
    { id: 'MAT-0200', sem: 4, nom: 'Estadística Descriptiva', pre: ['MAT-0110'], carrera: 'REDES' },
    { id: 'SIS-0125', sem: 4, nom: 'Base de Datos I', pre: ['SIS-0122'], carrera: 'REDES' },

    { id: 'ELC-0201', sem: 5, nom: 'Circuitos Eléctricos II', pre: ['ELC-0200'], carrera: 'REDES' },
    { id: 'ELC-0210', sem: 5, nom: 'Electrónica I', pre: ['ELC-0200'], carrera: 'REDES' },
    { id: 'RED-0120', sem: 5, nom: 'Instalación y Certificación de Redes', pre: ['RED-0100'], carrera: 'REDES' },
    { id: 'TEL-0210', sem: 5, nom: 'Fundamentos de los Sistemas de Comunicación', pre: ['TEL-0200'], carrera: 'REDES' },
    { id: 'SIS-0211', sem: 5, nom: 'Sistemas Operativos II', pre: ['SIS-0200'], carrera: 'REDES' },
    { id: 'SIS-0310', sem: 5, nom: 'Administración de Base de Datos I', pre: ['SIS-0125'], carrera: 'REDES' },

    { id: 'RED-0130', sem: 6, nom: 'Redes II', pre: ['RED-0100'], carrera: 'REDES' },
    { id: 'ELC-0215', sem: 6, nom: 'Electrónica II', pre: ['ELC-0210'], carrera: 'REDES' },
    { id: 'RED-0310', sem: 6, nom: 'Comunicaciones Digitales I', pre: ['TEL-0210'], carrera: 'REDES' },
    { id: 'TEL-0300', sem: 6, nom: 'Medios de Transmisión', pre: ['TEL-0210'], carrera: 'REDES' },
    { id: 'SIS-0230', sem: 6, nom: 'Taller de Sistemas Operativos II', pre: ['SIS-0211'], carrera: 'REDES' },
    { id: 'MAT-0210', sem: 6, nom: 'Estadistica Inferencial', pre: ['MAT-0200'], carrera: 'REDES' },

    { id: 'RED-0140', sem: 7, nom: 'Redes III', pre: ['RED-0130'], carrera: 'REDES' },
    { id: 'RED-0220', sem: 7, nom: 'Seguridad en Redes', pre: ['RED-0130'], carrera: 'REDES' },
    { id: 'RED-0210', sem: 7, nom: 'Tecnologías Inalámbricas', pre: ['RED-0210'], carrera: 'REDES'},
    { id: 'TEL-0320', sem: 7, nom: 'Antenas y Propagación', pre: ['TEL-0300'], carrera: 'REDES' },
    { id: 'ELE-0100', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'REDES', tipo: 'electiva'},
    { id: 'ELE-0200', sem: 7, nom: 'Electiva 2', pre: [], carrera: 'REDES', tipo: 'electiva'},

    { id: 'RED-0150', sem: 8, nom: 'Redes IV', pre: ['RED-0140'], carrera: 'REDES' },
    { id: 'SIS-0360', sem: 8, nom: 'Seguridad Informatica I', pre: ['RED-0220'], carrera: 'REDES' },
    { id: 'TEL-0330', sem: 8, nom: 'Sistemas de Comunicaciones Ópticas', pre: ['RED-0310'], carrera: 'REDES' },
    { id: 'TEL-0325', sem: 8, nom: 'Sistemas de Radiocomunicaciones I', pre: ['TEL-0320'], carrera: 'REDES' },
    { id: 'TEL-0340', sem: 8, nom: 'Telefonía Digital I', pre: ['RED-0310'], carrera: 'REDES' },
    { id: 'ELE-0300', sem: 8, nom: 'Electiva 3', pre: [], carrera: 'REDES', tipo: 'electiva'},

    { id: 'RED-0240', sem: 9, nom: 'Taller de Redes', pre: ['RED-0150'], carrera: 'REDES' },
    { id: 'ELE-0400', sem: 9, nom: 'Electiva 4', pre: [], carrera: 'REDES', tipo: 'electiva'},
    { id: 'TEL-0360', sem: 9, nom: 'Sistemas de Radiocomunicaciones II', pre: ['TEL-0325'], carrera: 'REDES' },
    { id: 'TEL-0350', sem: 9, nom: 'Redes Inalámbricas y Móviles', pre: ['TEL-0325'], carrera: 'REDES' },
    { id: 'ADM-0420', sem: 9, nom: 'Emprendedurismo', pre: ['LIN-0110'], carrera: 'REDES' },
    { id: 'ELE-0500', sem: 9, nom: 'Electiva 5', pre: [], carrera: 'REDES', tipo: 'electiva' },

    // ==========================================
    // CARRERA: INGENIERÍA DE SISTEMAS
    // ==========================================
    { id: 'SIS101', sem: 1, nom: 'Estructuras Discretas', pre: [], carrera: 'SISTEMAS' },
    { id: 'SIS102', sem: 1, nom: 'Fundamentos de Matemáticas', pre: [], carrera: 'SISTEMAS' },
    { id: 'SIS103', sem: 1, nom: 'Técnicas de Investigación', pre: [], carrera: 'SISTEMAS' },
    { id: 'SIS104', sem: 1, nom: 'Programación Básica', pre: [], carrera: 'SISTEMAS' },
    { id: 'SIS105', sem: 1, nom: 'Hardware y Software', pre: [], carrera: 'SISTEMAS' },
    { id: 'SIS106', sem: 1, nom: 'Inglés I', pre: [], carrera: 'SISTEMAS' },

    { id: 'SIS201', sem: 2, nom: 'Sistemas Digitales I', pre: ['SIS101'], carrera: 'SISTEMAS' },
    { id: 'SIS202', sem: 2, nom: 'Física I', pre: ['SIS102'], carrera: 'SISTEMAS' },
    { id: 'SIS203', sem: 2, nom: 'Álgebra Lineal', pre: ['SIS102'], carrera: 'SISTEMAS' },
    { id: 'SIS204', sem: 2, nom: 'Programación I', pre: ['SIS104'], carrera: 'SISTEMAS' },
    { id: 'SIS205', sem: 2, nom: 'Sistemas Operativos I', pre: ['SIS104'], carrera: 'SISTEMAS' },
    { id: 'SIS206', sem: 2, nom: 'Deontología y Prosocialidad', pre: [], carrera: 'SISTEMAS' },

    { id: 'SIS301', sem: 3, nom: 'Sistemas Digitales II', pre: ['SIS201'], carrera: 'SISTEMAS' },
    { id: 'SIS302', sem: 3, nom: 'Cálculo I', pre: ['SIS102'], carrera: 'SISTEMAS' },
    { id: 'SIS303', sem: 3, nom: 'Investigación Operativa', pre: ['SIS203'], carrera: 'SISTEMAS' },
    { id: 'SIS304', sem: 3, nom: 'Programación II', pre: ['SIS204'], carrera: 'SISTEMAS' },
    { id: 'SIS305', sem: 3, nom: 'Taller de Sistemas Operativos I', pre: ['SIS205'], carrera: 'SISTEMAS' },
    { id: 'SIS306', sem: 3, nom: 'Inglés II', pre: ['SIS106'], carrera: 'SISTEMAS' },

    { id: 'MAT-0200', sem: 4, nom: 'Estadística Descriptiva', pre: ['MAT-0100'], carrera: 'SISTEMAS' },
    { id: 'SIS-0140', sem: 4, nom: 'Diseño Web I', pre: ['SIS-0121'], carrera: 'SISTEMAS' },
    { id: 'RED-0100', sem: 4, nom: 'Redes I', pre: ['ELC-0110'], carrera: 'SISTEMAS' },
    { id: 'SIS-0123', sem: 4, nom: 'Programación III', pre: ['SIS-0122'], carrera: 'SISTEMAS' },
    { id: 'SIS-0125', sem: 4, nom: 'Base de Datos I', pre: ['SIS-0122'], carrera: 'SISTEMAS' },
    { id: 'CPA-0100', sem: 4, nom: 'Contabilidad Empresarial', pre: [], carrera: 'SISTEMAS' },

    { id: 'MAT-0210', sem: 5, nom: 'Estadística Inferencial', pre: ['MAT-0200'], carrera: 'SISTEMAS' },
    { id: 'SIS-0130', sem: 5, nom: 'Estructuras de Datos', pre: ['SIS-0123'], carrera: 'SISTEMAS' },
    { id: 'SIS-0126', sem: 5, nom: 'Base de Datos II', pre: ['SIS-0125'], carrera: 'SISTEMAS' },
    { id: 'SIS-0145', sem: 5, nom: 'Desarrollo de Sistemas I', pre: ['SIS-0125'], carrera: 'SISTEMAS' },
    { id: 'SIS-0300', sem: 5, nom: 'Programación Web I', pre: ['SIS-0125'], carrera: 'SISTEMAS' },
    { id: 'SIS-0211', sem: 5, nom: 'Sistemas Operativos II', pre: ['SIS-0200'], carrera: 'SISTEMAS' },

    { id: 'SIS-0310', sem: 6, nom: 'Administración de Base de Datos', pre: ['SIS-0126'], carrera: 'SISTEMAS' },
    { id: 'SIS-0320', sem: 6, nom: 'Sistemas de Información I', pre: ['SIS-0145'], carrera: 'SISTEMAS' },
    { id: 'SIS-0141', sem: 6, nom: 'Diseño Web II', pre: ['SIS-0140'], carrera: 'SISTEMAS' },
    { id: 'SIS-0150', sem: 6, nom: 'Tecnología Web I', pre: ['SIS-0125'], carrera: 'SISTEMAS' },
    { id: 'SIS-0301', sem: 6, nom: 'Programación Web II', pre: ['SIS-0300'], carrera: 'SISTEMAS' },
    { id: 'RED-0130', sem: 6, nom: 'Redes II', pre: ['RED-0100'], carrera: 'SISTEMAS' },

    { id: 'SIS-0250', sem: 7, nom: 'Inteligencia Artificial', pre: ['SIS-0130'], carrera: 'SISTEMAS' },
    { id: 'SIS-0321', sem: 7, nom: 'Sistemas de Información II', pre: ['SIS-0320'], carrera: 'SISTEMAS' },
    { id: 'ELE-0100', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'SISTEMAS', tipo: 'electiva' },
    { id: 'SIS-0330', sem: 7, nom: 'Desarrollo de Sistemas II', pre: ['SIS-0145'], carrera: 'SISTEMAS' },
    { id: 'SIS-0151', sem: 7, nom: 'Tecnología Web II', pre: ['SIS-0150'], carrera: 'SISTEMAS' },
    { id: 'SIS-0124', sem: 7, nom: 'Programación IV', pre: ['SIS-0123'], carrera: 'SISTEMAS' },

    { id: 'SIS-0325', sem: 8, nom: 'Ingeniería de Software I', pre: ['SIS-0321'], carrera: 'SISTEMAS' },
    { id: 'SIS-0322', sem: 8, nom: 'Sistemas de Información III', pre: ['SIS-0321'], carrera: 'SISTEMAS' },
    { id: 'SIS-0360', sem: 8, nom: 'Seguridad Informática I', pre: ['SIS-0321'], carrera: 'SISTEMAS' },
    { id: 'SIS-0350', sem: 8, nom: 'Tecnología de Base de Datos I', pre: ['SIS-0126'], carrera: 'SISTEMAS' },
    { id: 'SIS-0180', sem: 8, nom: 'Aplicaciones Móviles I', pre: ['SIS-0123'], carrera: 'SISTEMAS' },
    { id: 'ELE-0200', sem: 8, nom: 'Electiva 2', pre: [], carrera: 'SISTEMAS', tipo: 'electiva' },

    { id: 'SIS-0341', sem: 9, nom: 'Ingeniería de Software II', pre: ['SIS-0325'], carrera: 'SISTEMAS' },
    { id: 'INV-0170', sem: 9, nom: 'Inteligencia de Negocios', pre: ['SIS-0321'], carrera: 'SISTEMAS' },
    { id: 'SIS-0400', sem: 9, nom: 'Auditoría de Sistemas', pre: ['SIS-0360'], carrera: 'SISTEMAS' },
    { id: 'ELE-0300', sem: 9, nom: 'Electiva 3', pre: [], carrera: 'SISTEMAS', tipo: 'electiva' },
    { id: 'ADM-0420', sem: 9, nom: 'Emprendedurismo', pre: ['LIN-0110'], carrera: 'SISTEMAS' },
    { id: 'ELE-0400', sem: 9, nom: 'Electiva 4', pre: [], carrera: 'SISTEMAS', tipo: 'electiva' },

    // ==========================================
    // CARRERA: INGENIERÍA COMERCIAL
    // ==========================================
    { id: 'LIN-0150', sem: 1, nom: 'Lingüística', pre: [], carrera: 'COMERCIAL' },
    { id: 'MAT-0100', sem: 1, nom: 'Fundamentos de Matemáticas', pre: [], carrera: 'COMERCIAL' },
    { id: 'INV-0100', sem: 1, nom: 'Técnicas de Investigación', pre: [], carrera: 'COMERCIAL' },
    { id: 'ADM-0100', sem: 1, nom: 'Administración I', pre: [], carrera: 'COMERCIAL' },
    { id: 'ECO-0100', sem: 1, nom: 'Introducción a la Economía', pre: [], carrera: 'COMERCIAL' },
    { id: 'CPA-0100', sem: 1, nom: 'Contabilidad Empresarial I', pre: [], carrera: 'COMERCIAL' },

    { id: 'MAT-0200', sem: 2, nom: 'Estadística Descriptiva', pre: ['MAT-0100'], carrera: 'COMERCIAL' },
    { id: 'MAT-0120', sem: 2, nom: 'Cálculo I', pre: ['MAT-0100'], carrera: 'COMERCIAL' },
    { id: 'ADM-0200', sem: 2, nom: 'Investigación de Mercado I', pre: ['INV-0100'], carrera: 'COMERCIAL' },
    { id: 'ADM-0110', sem: 2, nom: 'Administración II', pre: ['ADM-0100'], carrera: 'COMERCIAL' },
    { id: 'ECO-0110', sem: 2, nom: 'Microeconomía I', pre: ['ECO-0100'], carrera: 'COMERCIAL' },
    { id: 'CPA-0110', sem: 2, nom: 'Contabilidad Empresarial II', pre: ['CPA-0100'], carrera: 'COMERCIAL' },

    { id: 'MAT-0210', sem: 3, nom: 'Estadística Inferencial', pre: ['MAT-0200'], carrera: 'COMERCIAL' },
    { id: 'LIN-0110', sem: 3, nom: 'Deontología y Prosocialidad', pre: [], carrera: 'COMERCIAL' },
    { id: 'ADM-0201', sem: 3, nom: 'Investigación de Mercado II', pre: ['ADM-0200'], carrera: 'COMERCIAL' },
    { id: 'ADM-0120', sem: 3, nom: 'Administración para la Toma de Decisiones', pre: ['ADM-0110'], carrera: 'COMERCIAL' },
    { id: 'ECO-0120', sem: 3, nom: 'Microeconomía II', pre: ['ECO-0110'], carrera: 'COMERCIAL' },
    { id: 'CPA-0200', sem: 3, nom: 'Contabilidad de Costos I', pre: ['CPA-0110'], carrera: 'COMERCIAL' },

    { id: 'MAT-0130', sem: 4, nom: 'Matemática Financiera', pre: ['MAT-0120'], carrera: 'COMERCIAL' },
    { id: 'CPA-0300', sem: 4, nom: 'Tributación Aplicada', pre: [], carrera: 'COMERCIAL' },
    { id: 'ADM-0210', sem: 4, nom: 'Principios de Marketing', pre: ['ADM-0201'], carrera: 'COMERCIAL' },
    { id: 'LIN-0250', sem: 4, nom: 'Liderazgo y Dinámica de Grupos', pre: ['ADM-0120'], carrera: 'COMERCIAL' },
    { id: 'ECO-0200', sem: 4, nom: 'Macroeconomía', pre: ['ECO-0120'], carrera: 'COMERCIAL' },
    { id: 'ADM-0300', sem: 4, nom: 'Finanzas Empresariales I', pre: ['CPA-0200'], carrera: 'COMERCIAL' },

    { id: 'MAT-0300', sem: 5, nom: 'Investigación Operativa', pre: ['MAT-0210'], carrera: 'COMERCIAL' },
    { id: 'ADM-0220', sem: 5, nom: 'Producto', pre: ['ADM-0210'], carrera: 'COMERCIAL' },
    { id: 'ADM-0230', sem: 5, nom: 'Precio', pre: ['ADM-0210'], carrera: 'COMERCIAL' },
    { id: 'ADM-0260', sem: 5, nom: 'Plaza', pre: ['ADM-0210'], carrera: 'COMERCIAL' },
    { id: 'PSI-0205', sem: 5, nom: 'Psicología de la Comunicación', pre: ['LIN-0250'], carrera: 'COMERCIAL' },
    { id: 'ADM-0310', sem: 5, nom: 'Finanzas Empresariales II', pre: ['ADM-0300'], carrera: 'COMERCIAL' },

    { id: 'DER-0330', sem: 6, nom: 'Derecho Comercial', pre: ['CPA-0300'], carrera: 'COMERCIAL' },
    { id: 'ADM-0410', sem: 6, nom: 'Responsabilidad Social Empresarial', pre: ['LIN-0110'], carrera: 'COMERCIAL' },
    { id: 'ADM-0250', sem: 6, nom: 'Planificación de Marketing', pre: ['ADM-0210'], carrera: 'COMERCIAL' },
    { id: 'ADM-0140', sem: 6, nom: 'Gestión de Recursos Humanos', pre: ['LIN-0250'], carrera: 'COMERCIAL' },
    { id: 'ADM-0420', sem: 6, nom: 'Emprendedurismo', pre: ['ADM-0120'], carrera: 'COMERCIAL' },
    { id: 'MKT-0350', sem: 6, nom: 'Comercio Exterior', pre: ['ECO-0200'], carrera: 'COMERCIAL' },

    { id: 'IND-0300', sem: 7, nom: 'Gestión de la Calidad I', pre: ['MAT-0300'], carrera: 'COMERCIAL' },
    { id: 'MKT-0150', sem: 7, nom: 'Comportamiento del Consumidor', pre: ['PSI-0205'], carrera: 'COMERCIAL' },
    { id: 'LIN-0220', sem: 7, nom: 'Comunicación Publicitaria y Propagandistica', pre: ['ADM-0260'], carrera: 'COMERCIAL' },
    { id: 'MKT-0400', sem: 7, nom: 'Insight', pre: ['ADM-0420'], carrera: 'COMERCIAL' },
    { id: 'IND-0400', sem: 7, nom: 'Preparación y Evaluación de Proyectos I', pre: ['ADM-0310'], carrera: 'COMERCIAL' },
    { id: 'MKT-0340', sem: 7, nom: 'Marketing Internacional', pre: ['MKT-0350'], carrera: 'COMERCIAL' },

    { id: 'MKT-0410', sem: 8, nom: 'Servicio al Cliente', pre: ['IND-0300'], carrera: 'COMERCIAL' },
    { id: 'MKT-0360', sem: 8, nom: 'Gestión de Marketing de Servicios e Industrial', pre: ['MKT-0150'], carrera: 'COMERCIAL' },
    { id: 'ELE-0100', sem: 8, nom: 'Electiva 1', pre: [], carrera: 'COMERCIAL', tipo: 'electiva' },
    { id: 'ELE-0200', sem: 8, nom: 'Electiva 2', pre: [], carrera: 'COMERCIAL', tipo: 'electiva' },
    { id: 'ELE-0300', sem: 8, nom: 'Electiva 3', pre: [], carrera: 'COMERCIAL', tipo: 'electiva' },
    { id: 'ADM-0325', sem: 8, nom: 'Trading', pre: ['MKT-0340'], carrera: 'COMERCIAL' },

    // ==========================================
    // CARRERA: PSICOLOGÍA
    // ==========================================
    { id: 'SOC-0100', sem: 1, nom: 'Sociología', pre: [], carrera: 'PSICOLOGIA' },
    { id: 'INV-0100', sem: 1, nom: 'Técnicas Investigación', pre: [], carrera: 'PSICOLOGIA' },
    { id: 'FIL-0100', sem: 1, nom: 'Filosofía', pre: [], carrera: 'PSICOLOGIA' },
    { id: 'LIN-0110', sem: 1, nom: 'Deontología y Prosocialidad', pre: [], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0115', sem: 1, nom: 'Psicobiología', pre: [], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0120', sem: 1, nom: 'Escuelas Psicológicas', pre: [], carrera: 'PSICOLOGIA' },

    { id: 'PSI-0110', sem: 2, nom: 'Psicología Social I', pre: ['SOC-0100'], carrera: 'PSICOLOGIA' },
    { id: 'HIS-0250', sem: 2, nom: 'Formación Social Boliviana', pre: ['SOC-0100'], carrera: 'PSICOLOGIA' },
    { id: 'SOC-0110', sem: 2, nom: 'Antropología', pre: ['FIL-0100'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0135', sem: 2, nom: 'Psicolingüística', pre: ['FIL-0100'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0125', sem: 2, nom: 'Neurología I', pre: ['PSI-0115'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0130', sem: 2, nom: 'Teorías de la Personalidad', pre: ['PSI-0120'], carrera: 'PSICOLOGIA' },

    { id: 'PSI-0111', sem: 3, nom: 'Psicología Social II', pre: ['PSI-0110'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0250', sem: 3, nom: 'Etnopsicología', pre: ['SOC-0110'], carrera: 'PSICOLOGIA' },
    { id: 'ADM-0100', sem: 3, nom: 'Administración I', pre: ['LIN-0110'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0145', sem: 3, nom: 'Desarrollo Evolutivo', pre: ['PSI-0125'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0140', sem: 3, nom: 'Psicología Experimental', pre: ['PSI-0130'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0160', sem: 3, nom: 'Psicología Aprendizaje', pre: ['PSI-0130'], carrera: 'PSICOLOGIA' },

    { id: 'PSI-0200', sem: 4, nom: 'Psicología Comunicacional', pre: ['PSI-0111'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0260', sem: 4, nom: 'Psicología Sistémica', pre: ['PSI-0111'], carrera: 'PSICOLOGIA' },
    { id: 'MAT-0200', sem: 4, nom: 'Estadística Descriptiva', pre: ['INV-0100'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0215', sem: 4, nom: 'Comportamiento Organizacional', pre: ['ADM-0100'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0170', sem: 4, nom: 'Psicoanálisis I', pre: ['PSI-0160'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0210', sem: 4, nom: 'Psicología Cognitiva', pre: ['PSI-0145'], carrera: 'PSICOLOGIA' },
    

    { id: 'PSI-0300', sem: 5, nom: 'Psicología Institucional', pre: ['PSI-0200'], carrera: 'PSICOLOGIA' },
    { id: 'LIN-0250', sem: 5, nom: 'Liderazgo y Dinámica de Grupos', pre: ['PSI-0215'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0180', sem: 5, nom: 'Psicometría', pre: ['PSI-0210'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0235', sem: 5, nom: 'Psicopatología', pre: ['PSI-0170'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0220', sem: 5, nom: 'Psicología Educativa', pre: ['PSI-0210'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0171', sem: 5, nom: 'Psicoanálisis II', pre: ['PSI-0170'], carrera: 'PSICOLOGIA' },

    { id: 'PSI-0310', sem: 6, nom: 'Intervención Socio Comunitaria', pre: ['PSI-0300'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0230', sem: 6, nom: 'Dificultades de Aprendizaje', pre: ['PSI-0220'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0245', sem: 6, nom: 'Taller de Técnicas Proyectivas', pre: ['PSI-0180'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0330', sem: 6, nom: 'Psicofarmacología', pre: ['PSI-0235'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0240', sem: 6, nom: 'Técnicas Proyectivas I', pre: ['PSI-0180'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0320', sem: 6, nom: 'Entrevistas Psicológicas', pre: ['PSI-0171'], carrera: 'PSICOLOGIA' },

    { id: 'ADM-0140', sem: 7, nom: 'Gestión Recursos Humanos', pre: ['LIN-0250'], carrera: 'PSICOLOGIA' },
    { id: 'ELE-0100', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'PSICOLOGIA', tipo: 'electiva' },
    { id: 'INV-0110', sem: 7, nom: 'Métodos y Técnicas de Investigación Aplicada', pre: ['MAT-0200'], carrera: 'PSICOLOGIA' },
    { id: 'ELE-0200', sem: 7, nom: 'Electiva 2', pre: [], carrera: 'PSICOLOGIA', tipo: 'electiva' },
    { id: 'PSI-0241', sem: 7, nom: 'Técnicas Proyectivas II', pre: ['PSI-0240'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0400', sem: 7, nom: 'Clínica I', pre: ['PSI-0320'], carrera: 'PSICOLOGIA' },

    { id: 'LIN-0210', sem: 8, nom: 'Orientación Vocacional', pre: ['ADM-0140'], carrera: 'PSICOLOGIA' },
    { id: 'ADM-0420', sem: 8, nom: 'Emprendedurismo', pre: ['LIN-0250'], carrera: 'PSICOLOGIA' },
    { id: 'ELE-0300', sem: 8, nom: 'Electiva 3', pre: [], carrera: 'PSICOLOGIA', tipo: 'electiva' },
    { id: 'PSI-0242', sem: 8, nom: 'Técnicas Proyectivas III', pre: ['PSI-0241'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0410', sem: 8, nom: 'Psicodiagnóstico', pre: ['PSI-0410'], carrera: 'PSICOLOGIA' },
    { id: 'PSI-0401', sem: 8, nom: 'Clínica II', pre: ['PSI-0400'], carrera: 'PSICOLOGIA' },

    // ==========================================
    // CARRERA: DERECHO
    // ==========================================
    { id: 'DER-0100', sem: 1, nom: 'Derecho Romano', pre: [], carrera: 'DERECHO' },
    { id: 'DER-0110', sem: 1, nom: 'Introducción al Derecho', pre: [], carrera: 'DERECHO' },
    { id: 'DER-0400', sem: 1, nom: 'Criminología', pre: [], carrera: 'DERECHO' },
    { id: 'DER-0130', sem: 1, nom: 'Teoría del Estado', pre: [], carrera: 'DERECHO' },
    { id: 'SOC-0120', sem: 1, nom: 'Sociología Jurídica', pre: [], carrera: 'DERECHO' },
    { id: 'INV-0100', sem: 1, nom: 'Técnicas de Investigación', pre: [], carrera: 'DERECHO' },

    { id: 'DER-0300', sem: 2, nom: 'Derecho Civil I', pre: ['DER-0100'], carrera: 'DERECHO' },
    { id: 'DER-0401', sem: 2, nom: 'Derecho Penal I', pre: ['DER-0400'], carrera: 'DERECHO' },
    { id: 'DER-0220', sem: 2, nom: 'Derechos Humanos', pre: ['SOC-0120'], carrera: 'DERECHO' },
    { id: 'DER-0210', sem: 2, nom: 'Derecho Constitucional I', pre: ['DER-0130'], carrera: 'DERECHO' },
    { id: 'LIN-0110', sem: 2, nom: 'Deontología y Prosocialidad', pre: [], carrera: 'DERECHO' },
    { id: 'ECO-0220', sem: 2, nom: 'Economía Política', pre: [], carrera: 'DERECHO' },

    { id: 'DER-0301', sem: 3, nom: 'Derecho Civil II', pre: ['DER-0300'], carrera: 'DERECHO' },
    { id: 'DER-0402', sem: 3, nom: 'Derecho Penal II', pre: ['DER-0401'], carrera: 'DERECHO' },
    { id: 'DER-0240', sem: 3, nom: 'Ley del Órgano Judicial', pre: ['DER-0210'], carrera: 'DERECHO' },
    { id: 'DER-0211', sem: 3, nom: 'Derecho Constitucional II', pre: ['DER-0210'], carrera: 'DERECHO' },
    { id: 'FIL-0120', sem: 3, nom: 'Filosofía del Derecho', pre: ['LIN-0110'], carrera: 'DERECHO' },
    { id: 'DER-0340', sem: 3, nom: 'Derecho Económico y Financiero', pre: ['ECO-0220'], carrera: 'DERECHO' },

    { id: 'DER-0302', sem: 4, nom: 'Derecho Civil III', pre: ['DER-0301'], carrera: 'DERECHO' },
    { id: 'DER-0255', sem: 4, nom: 'Derecho Minero e Hidrocarburifero', pre: ['DER-0301'], carrera: 'DERECHO' },
    { id: 'DER-0420', sem: 4, nom: 'Medicina Legal', pre: ['DER-0402'], carrera: 'DERECHO' },
    { id: 'DER-0410', sem: 4, nom: 'Psiquiatría Forense', pre: ['DER-0400'], carrera: 'DERECHO' },
    { id: 'DER-0230', sem: 4, nom: 'Derecho Agroambiental I', pre: ['DER-0211'], carrera: 'DERECHO' },
    { id: 'DER-0241', sem: 4, nom: 'Derecho Administrativo y Regulatorio', pre: ['DER-0211'], carrera: 'DERECHO' },

    { id: 'DER-0303', sem: 5, nom: 'Derecho Civil IV', pre: ['DER-0302'], carrera: 'DERECHO' },
    { id: 'DER-0330', sem: 5, nom: 'Derecho Comercial I', pre: ['DER-0301'], carrera: 'DERECHO' },
    { id: 'DER-0120', sem: 5, nom: 'Derecho de los Pueblos, Indígenas, Originarios y Campesinos', pre: ['DER-0220'], carrera: 'DERECHO' },
    { id: 'DER-0260', sem: 5, nom: 'Derecho de Familia Niño, Niña y Adolescente', pre: ['DER-0240'], carrera: 'DERECHO' },
    { id: 'DER-0242', sem: 5, nom: 'Derecho Autonómico', pre: ['DER-0211'], carrera: 'DERECHO' },
    { id: 'DER-0231', sem: 5, nom: 'Derecho Agroambiental II', pre: ['DER-0230'], carrera: 'DERECHO' },

    { id: 'DER-0304', sem: 6, nom: 'Derecho Civil V', pre: ['DER-0303'], carrera: 'DERECHO' },
    { id: 'DER-0250', sem: 6, nom: 'Derecho Laboral y Social', pre: ['DER-0303'], carrera: 'DERECHO' },
    { id: 'DER-0270', sem: 6, nom: 'Derecho Internacional Público', pre: ['DER-0220'], carrera: 'DERECHO' },
    { id: 'DER-0331', sem: 6, nom: 'Derecho Comercial II', pre: ['DER-0330'], carrera: 'DERECHO' },
    { id: 'DER-0345', sem: 6, nom: 'Derecho del Consumidor', pre: ['DER-0330'], carrera: 'DERECHO' },
    { id: 'ADM-0420', sem: 6, nom: 'Emprendedurismo', pre: ['INV-0100'], carrera: 'DERECHO' },

    { id: 'DER-0310', sem: 7, nom: 'Procedimiento Civil', pre: ['DER-0304'], carrera: 'DERECHO' },
    { id: 'DER-0430', sem: 7, nom: 'Procedimiento Penal', pre: ['DER-0402'], carrera: 'DERECHO' },
    { id: 'DER-0280', sem: 7, nom: 'Derecho Internacional Privado', pre: ['DER-0331'], carrera: 'DERECHO' },
    { id: 'DER-0335', sem: 7, nom: 'Derecho y Procedimiento Tributario', pre: ['DER-0331'], carrera: 'DERECHO' },
    { id: 'DER-0215', sem: 7, nom: 'Procedimiento Constitucional', pre: ['DER-0211'], carrera: 'DERECHO' },
    { id: 'LIN-0115', sem: 7, nom: 'Gramatica y Argumentación Jurídica', pre: ['LIN-0110'], carrera: 'DERECHO' },

    { id: 'DER-0360', sem: 8, nom: 'Métodos Alternos de Solución de Conflictos', pre: ['DER-0310'], carrera: 'DERECHO' },
    { id: 'DER-0320', sem: 8, nom: 'Clínica Legal I', pre: ['DER-0310'], carrera: 'DERECHO' },
    { id: 'DER-0440', sem: 8, nom: 'Clínica Legal II', pre: ['DER-0430'], carrera: 'DERECHO' },
    { id: 'ELE-0100', sem: 8, nom: 'Electiva 1', pre: [], carrera: 'DERECHO', tipo: 'electiva' },
    { id: 'ELE-0200', sem: 8, nom: 'Electiva 2', pre: [], carrera: 'DERECHO', tipo: 'electiva' },
    { id: 'ELE-0300', sem: 8, nom: 'Electiva 3', pre: [], carrera: 'DERECHO', tipo: 'electiva' },

    // ==========================================
    // 1. ADMINISTRACIÓN DE EMPRESAS
    // ==========================================
    { id: 'LIN-0150', sem: 1, nom: 'Lingüística', pre: [], carrera: 'ADMINISTRACION' },
    { id: 'MAT-0100', sem: 1, nom: 'Fundamentos de Matemáticas', pre: [], carrera: 'ADMINISTRACION' },
    { id: 'INV-0100', sem: 1, nom: 'Técnicas de Investigación', pre: [], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0100', sem: 1, nom: 'Administración I', pre: [], carrera: 'ADMINISTRACION' },
    { id: 'ECO-0100', sem: 1, nom: 'Introducción a la Economía', pre: [], carrera: 'ADMINISTRACION' },
    { id: 'CPA-0100', sem: 1, nom: 'Contabilidad Empresarial I', pre: [], carrera: 'ADMINISTRACION' },
    
    { id: 'MAT-0200', sem: 2, nom: 'Estadística Descriptiva', pre: ['MAT-0100'], carrera: 'ADMINISTRACION' },
    { id: 'MAT-0120', sem: 2, nom: 'Cálculo I', pre: ['MAT-0100'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0200', sem: 2, nom: 'Investigación de Mercado I', pre: ['INV-0100'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0110', sem: 2, nom: 'Administración II', pre: ['ADM-0100'], carrera: 'ADMINISTRACION' },
    { id: 'ECO-0110', sem: 2, nom: 'Microeconomía I', pre: ['ECO-0100'], carrera: 'ADMINISTRACION' },
    { id: 'CPA-0110', sem: 2, nom: 'Contabilidad Empresarial II', pre: ['CPA-0100'], carrera: 'ADMINISTRACION' },
    
    { id: 'MAT-0210', sem: 3, nom: 'Estadística Inferencial', pre: ['MAT-0200'], carrera: 'ADMINISTRACION' },
    { id: 'LIN-0110', sem: 3, nom: 'Deontología y Prosocialidad', pre: [], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0201', sem: 3, nom: 'Investigación de Mercado II', pre: ['ADM-0200'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0120', sem: 3, nom: 'Administración para la Toma de Decisiones', pre: ['ADM-0110'], carrera: 'ADMINISTRACION' },
    { id: 'ECO-0120', sem: 3, nom: 'Microeconomía II', pre: ['ECO-0110'], carrera: 'ADMINISTRACION' },
    { id: 'CPA-0200', sem: 3, nom: 'Contabilidad de Costos I', pre: ['CPA-0110'], carrera: 'ADMINISTRACION' },

    { id: 'MAT-0130', sem: 4, nom: 'Matemática Financiera', pre: ['MAT-0120'], carrera: 'ADMINISTRACION' },
    { id: 'CPA-0300', sem: 4, nom: 'Tributación Aplicada I', pre: [], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0140', sem: 4, nom: 'Gestión de Recursos Humanos', pre: ['ADM-0120'], carrera: 'ADMINISTRACION' },
    { id: 'LIN-0250', sem: 4, nom: 'Liderazgo y Dinámica de Grupos', pre: ['ADM-0120'], carrera: 'ADMINISTRACION' },
    { id: 'ECO-0200', sem: 4, nom: 'Macroeconomía', pre: ['ECO-0120'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0300', sem: 4, nom: 'Finanzas Empresariales I', pre: ['ECO-0120'], carrera: 'ADMINISTRACION' },

    { id: 'DER-0330', sem: 5, nom: 'Derecho Comercial I', pre: ['CPA-0300'], carrera: 'ADMINISTRACION' },
    { id: 'MAT-0300', sem: 5, nom: 'Investigación Operativa I', pre: ['MAT-0210'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0210', sem: 5, nom: 'Principios de Marketing', pre: ['ADM-0201'], carrera: 'ADMINISTRACION' },
    { id: 'PSI-0215', sem: 5, nom: 'Comportamiento Organizacional', pre: ['ADM-0120'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0130', sem: 5, nom: 'Organizacion y Sistemas', pre: ['ADM-0120'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0310', sem: 5, nom: 'Finanzas Empresariales II', pre: ['ADM-0300'], carrera: 'ADMINISTRACION' },

    { id: 'DER-0250', sem: 6, nom: 'Derecho Laboral y Social', pre: ['CPA-0300'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0250', sem: 6, nom: 'Planificación de Marketing', pre: ['ADM-0210'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0220', sem: 6, nom: 'Producto', pre: ['ADM-0210'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0230', sem: 6, nom: 'Precio', pre: ['ADM-0210'], carrera: 'ADMINISTRACION' },
    { id: 'IND-0100', sem: 6, nom: 'Producción y Manofactura Flexible I', pre: ['CPA-0200'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0320', sem: 6, nom: 'Finanzas Empresariales III', pre: ['ADM-0310'], carrera: 'ADMINISTRACION' },

    { id: 'IND-0300', sem: 7, nom: 'Gestión de la Calidad I', pre: ['MAT-0300'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0400', sem: 7, nom: 'Administración Publica', pre: ['ADM-0140'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0260', sem: 7, nom: 'Plaza', pre: ['ADM-0210'], carrera: 'ADMINISTRACION' },
    { id: 'INV-0101', sem: 7, nom: 'Producción y Manofactura Flexible II', pre: ['INV-0100'], carrera: 'ADMINISTRACION' },
    { id: 'ADM-0410', sem: 7, nom: 'Responsabilidad Social Empresarial', pre: ['LIN-0250'], carrera: 'ADMINISTRACION' },
    { id: 'IND-0400', sem: 7, nom: 'Preparación y Evaluación de Proyectos I', pre: ['ADM-0320'], carrera: 'ADMINISTRACION' },

    { id: 'ELE-0100', sem: 8, nom: 'Electiva 1', pre: [], carrera: 'ADMINISTRACION', tipo: 'electiva' },
    { id: 'ADM-0401', sem: 8, nom: 'Gestión Municipal', pre: ['ADM-0400'], carrera: 'ADMINISTRACION' },
    { id: 'ELE-0200', sem: 8, nom: 'Electiva 2', pre: [], carrera: 'ADMINISTRACION', tipo: 'electiva' },
    { id: 'ELE-0300', sem: 8, nom: 'Electiva 3', pre: [], carrera: 'ADMINISTRACION', tipo: 'electiva' },
    { id: 'ADM-0420', sem: 8, nom: 'Emprendedurismo', pre: ['ADM-0410'], carrera: 'ADMINISTRACION' },
    { id: 'MKT-0350', sem: 8, nom: 'Comercio Exterior', pre: ['ECO-0200'], carrera: 'ADMINISTRACION' },

    // ==========================================
    // 2. COMUNICACIÓN SOCIAL
    // ==========================================
    { id: 'LIN-0150', sem: 1, nom: 'Lingüística', pre: [], carrera: 'COMUNICACION' },
    { id: 'HIS-0110', sem: 1, nom: 'Historia de la Comunicación', pre: [], carrera: 'COMUNICACION' },
    { id: 'LIN-0110', sem: 1, nom: 'Deontología y Prosocialidad', pre: [], carrera: 'COMUNICACION' },
    { id: 'INV-0100', sem: 1, nom: 'Técnicas de Investigación', pre: [], carrera: 'COMUNICACION' },
    { id: 'HIS-0200', sem: 1, nom: 'Historia Sociopolítica Boliviana', pre: [], carrera: 'COMUNICACION' },
    { id: 'COM-0110', sem: 1, nom: 'Técnicas de Oratoria', pre: [], carrera: 'COMUNICACION' },

    
    { id: 'LIN-0170', sem: 2, nom: 'Redacción y Estilo', pre: ['LIN-0150'], carrera: 'COMUNICACION' },
    { id: 'LIN-0125', sem: 2, nom: 'Semiótica y Lenguaje de la Imagen', pre: ['LIN-0150'], carrera: 'COMUNICACION' },
    { id: 'COM-0120', sem: 2, nom: 'Teorías y modelos de la Comunicación', pre: ['HIS-0110'], carrera: 'COMUNICACION' },
    { id: 'PSI-0205', sem: 2, nom: 'Psicología de la Comunicación', pre: ['LIN-0110'], carrera: 'COMUNICACION' },
    { id: 'MAT-0200', sem: 2, nom: 'Estadística Descriptiva', pre: ['INV-0100'], carrera: 'COMUNICACION' },
    { id: 'COM-0125', sem: 2, nom: 'Analisis Critico de la Realidad Nacional e Internacional', pre: ['HIS-0200'], carrera: 'COMUNICACION' },
    
    { id: 'LIN-0120', sem: 3, nom: 'Redacción Periodística y Género de Información', pre: ['LIN-0170'], carrera: 'COMUNICACION' },
    { id: 'COM-0200', sem: 3, nom: 'Documentación Periodistica', pre: ['LIN-0170'], carrera: 'COMUNICACION' },
    { id: 'COM-0215', sem: 3, nom: 'Fotografía', pre: ['LIN-0125'], carrera: 'COMUNICACION' },
    { id: 'REL-0210', sem: 3, nom: 'Comunicación Organizacional', pre: ['PSI-0205'], carrera: 'COMUNICACION' },
    { id: 'INV-0110', sem: 3, nom: 'Métodos y Técnicas de Investigación Aplicada', pre: ['MAT-0200'], carrera: 'COMUNICACION' },
    { id: 'COM-0130', sem: 3, nom: 'Comunicación Género y Cultura de Masas en el Mundo Comptemporaneo', pre: ['COM-0125'], carrera: 'COMUNICACION' },
    
    { id: 'LIN-0121', sem: 4, nom: 'Redacción Periodística y Género de Opinión', pre: ['LIN-0120'], carrera: 'COMUNICACION' },
    { id: 'COM-0225', sem: 4, nom: 'Comunicación Audiovisual y Radial', pre: ['COM-0215'], carrera: 'COMUNICACION' },
    { id: 'COM-0205', sem: 4, nom: 'Herramientas Digitales', pre: ['COM-0215'], carrera: 'COMUNICACION' },
    { id: 'COM-0140', sem: 4, nom: 'Opinión Pública y Auditoria de Medios', pre: ['REL-0210'], carrera: 'COMUNICACION' },
    { id: 'REL-0220', sem: 4, nom: 'Gestión de la Comunicación de Crisis', pre: ['REL-0210'], carrera: 'COMUNICACION' },
    { id: 'COM-0245', sem: 4, nom: 'Observatorio de Medios', pre: ['INV-0110'], carrera: 'COMUNICACION' },
    
    { id: 'INV-0150', sem: 5, nom: 'Investigación Periodistica', pre: ['LIN-0121'], carrera: 'COMUNICACION' },
    { id: 'LIN-0220', sem: 5, nom: 'Comunicación Publicitaria y Propagandistica', pre: ['COM-0225'], carrera: 'COMUNICACION' },
    { id: 'COM-0206', sem: 5, nom: 'Diseño Grafico Especializado', pre: ['COM-0205'], carrera: 'COMUNICACION' },
    { id: 'COM-0230', sem: 5, nom: 'Técnicas Televisivas I', pre: ['COM-0225'], carrera: 'COMUNICACION' },
    { id: 'REL-0230', sem: 5, nom: 'Gestión Estratégica de la RSE y Creación de Valor', pre: ['REL-0220'], carrera: 'COMUNICACION' },
    { id: 'CPA-0135', sem: 5, nom: 'Contabilidad Presupuestaria', pre: ['INV-0110'], carrera: 'COMUNICACION' },
    
    
    { id: 'COM-0210', sem: 6, nom: 'Redacción de Informes y Boletines de Prensa', pre: ['INV-0150'], carrera: 'COMUNICACION' },
    { id: 'COM-0340', sem: 6, nom: 'Planificación Estratégica de Medios', pre: ['LIN-0220'], carrera: 'COMUNICACION' },
    { id: 'COM-0207', sem: 6, nom: 'Periodismo Digital', pre: ['COM-0206'], carrera: 'COMUNICACION' },
    { id: 'COM-0231', sem: 6, nom: 'Técnicas Televisivas II', pre: ['COM-0230'], carrera: 'COMUNICACION' },
    { id: 'REL-0401', sem: 6, nom: 'DIRCOM', pre: ['REL-0230'], carrera: 'COMUNICACION' },
    { id: 'COM-0350', sem: 6, nom: 'Proyectos de Desarrollo Social en Comunicación', pre: ['INV-0110'], carrera: 'COMUNICACION' },


    { id: 'COM-0220', sem: 7, nom: 'Redacción y Difusión de Materiales Impresos', pre: ['COM-0210'], carrera: 'COMUNICACION' },
    { id: 'REL-0350', sem: 7, nom: 'Community Manager', pre: ['COM-0207'], carrera: 'COMUNICACION' },
    { id: 'COM-0250', sem: 7, nom: 'Producción Radiofónica', pre: ['COM-0231'], carrera: 'COMUNICACION' },
    { id: 'COM-0240', sem: 7, nom: 'Cine y Guionaje', pre: ['COM-0231'], carrera: 'COMUNICACION' },
    { id: 'DER-0365', sem: 7, nom: 'Negociación y Concentración', pre: ['REL-0220'], carrera: 'COMUNICACION' },
    { id: 'ADM-0420', sem: 7, nom: 'Emprendedurismo', pre: ['CPA-0135'], carrera: 'COMUNICACION' },
   
    { id: 'ELE-0100', sem: 8, nom: 'Electiva 1', pre: [], carrera: 'COMUNICACION' },
    { id: 'ELE-0200', sem: 8, nom: 'Electiva 2', pre: [], carrera: 'COMUNICACION' },
    { id: 'COM-0255', sem: 8, nom: 'Producción Televisiva y Radial', pre: ['COM-0250'], carrera: 'COMUNICACION' },
    { id: 'COM-0400', sem: 8, nom: 'Comunicación Comunitaria en Salud y Educación', pre: ['COM-0350'], carrera: 'COMUNICACION' },
    { id: 'DER-0315', sem: 8, nom: 'Legislación de la Comunicación', pre: ['DER-0365'], carrera: 'COMUNICACION' },
    { id: 'COM-0410', sem: 8, nom: 'Comunicación Alternativa y Minimedios', pre: ['COM-0350'], carrera: 'COMUNICACION' },

    // ==========================================
    // 3. CONTADURÍA PÚBLICA
    // ==========================================
    { id: 'MAT-0100', sem: 1, nom: 'Fundamentos de Matemáticas', pre: [], carrera: 'CONTADURIA' },
    { id: 'INV-0100', sem: 1, nom: 'Técnicas de Investigación', pre: [], carrera: 'CONTADURIA' },
    { id: 'LIN-0110', sem: 1, nom: 'Deontología y Prosocialidad', pre: [], carrera: 'CONTADURIA' },
    { id: 'ADM-0100', sem: 1, nom: 'Administración I', pre: [], carrera: 'CONTADURIA' },
    { id: 'ECO-0100', sem: 1, nom: 'Introducción a la Enconomía', pre: [], carrera: 'CONTADURIA' },
    { id: 'CPA-0100', sem: 1, nom: 'Contabilidad Empresarial I', pre: [], carrera: 'CONTADURIA' },
    
    { id: 'MAT-0120', sem: 2, nom: 'Cálculo I', pre: ['MAT-0100'], carrera: 'CONTADURIA' },
    { id: 'DER-0330', sem: 2, nom: 'Derecho Comercial I', pre: [], carrera: 'CONTADURIA' },
    { id: 'ADM-0110', sem: 2, nom: 'Administración II', pre: ['ADM-0100'], carrera: 'CONTADURIA' },
    { id: 'ECO-0110', sem: 2, nom: 'Microeconomia I', pre: ['ECO-0100'], carrera: 'CONTADURIA' },
    { id: 'CPA-0115', sem: 2, nom: 'Normas Contables', pre: ['CPA-0100'], carrera: 'CONTADURIA' },
    { id: 'CPA-0110', sem: 2, nom: 'Contabilidad Empresarial II', pre: ['CPA-0100'], carrera: 'CONTADURIA' },
    
    { id: 'MAT-0200', sem: 3, nom: 'Estadística Descriptiva', pre: ['MAT-0120'], carrera: 'CONTADURIA' },
    { id: 'MAT-0130', sem: 3, nom: 'Matemática Financiera', pre: ['MAT-0120'], carrera: 'CONTADURIA' },
    { id: 'DER-250', sem: 3, nom: 'Derecho Laboral y Social', pre: ['DER-0330'], carrera: 'CONTADURIA' },
    { id: 'ADM-0130', sem: 3, nom: 'Organización y Sistemas', pre: ['ADM-0110'], carrera: 'CONTADURIA' },
    { id: 'ECO-0200', sem: 3, nom: 'Macroeconomia', pre: ['ECO-0110'], carrera: 'CONTADURIA' },
    { id: 'CPA-0120', sem: 3, nom: 'Contabilidad Empresarial III', pre: ['CPA-0110'], carrera: 'CONTADURIA' },
    
    { id: 'MAT-0210', sem: 4, nom: 'Estadística Inferencial', pre: ['MAT-0200'], carrera: 'CONTADURIA' },
    { id: 'CPA-0300', sem: 4, nom: 'Tributación Aplicada I', pre: ['DER-0330'], carrera: 'CONTADURIA' },
    { id: 'CPA-0200', sem: 4, nom: 'Contabilidad de Costos I', pre: ['CPA-0120'], carrera: 'CONTADURIA' },
    { id: 'CPA-0340', sem: 4, nom: 'Contabilidad Petrolera', pre: ['CPA-0120'], carrera: 'CONTADURIA' },
    { id: 'CPA-0330', sem: 4, nom: 'Contabilidad Gubernamental', pre: ['CPA-0120'], carrera: 'CONTADURIA' },
    { id: 'CPA-0130', sem: 4, nom: 'Contabilidad Empresarial IV', pre: ['CPA-0120'], carrera: 'CONTADURIA' },
    
    { id: 'ADM-0300', sem: 5, nom: 'Finanzas Empresariales I', pre: ['MAT-0130'], carrera: 'CONTADURIA' },
    { id: 'CPA-0310', sem: 5, nom: 'Tributación Aplicada II', pre: ['CPA-0300'], carrera: 'CONTADURIA' },
    { id: 'CPA-0210', sem: 5, nom: 'Contabilidad de Costos II', pre: ['CPA-0200'], carrera: 'CONTADURIA' },
    { id: 'CPA-0360', sem: 5, nom: 'Contabilidad Minera', pre: ['CPA-0130'], carrera: 'CONTADURIA' },
    { id: 'CPA-0350', sem: 5, nom: 'Contabilidad de Entidades Financieras', pre: ['CPA-0130'], carrera: 'CONTADURIA' },
    { id: 'CPA-0140', sem: 5, nom: 'Contabilidad Superior', pre: ['CPA-0130'], carrera: 'CONTADURIA' },
   
    { id: 'ADM-0310', sem: 6, nom: 'Finanzas Empresariales II', pre: ['ADM-0300'], carrera: 'CONTADURIA' },
    { id: 'ADM-0420', sem: 6, nom: 'Emprendedurismo', pre: ['LIN-0110'], carrera: 'CONTADURIA' },
    { id: 'CPA-0370', sem: 6, nom: 'Contabilidad Agropecuaria', pre: ['CPA-0130'], carrera: 'CONTADURIA' },
    { id: 'CPA-0450', sem: 6, nom: 'Análisis e Interpretación de Estados Financieros', pre: ['CPA-0140'], carrera: 'CONTADURIA' },
    { id: 'CPA-0400', sem: 6, nom: 'Auditoría I', pre: ['CPA-0140'], carrera: 'CONTADURIA' },
    { id: 'CPA-0390', sem: 6, nom: 'Gabinete Contable', pre: ['CPA-0140'], carrera: 'CONTADURIA' },


    { id: 'ELE-0100', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'CONTADURIA', tipo: 'electiva' },
    { id: 'ELE-0200', sem: 7, nom: 'Electiva 2', pre: [], carrera: 'CONTADURIA', tipo: 'electiva' },
    { id: 'CPA-0465', sem: 7, nom: 'Presupuestos y Planificación', pre: ['CPA-0450'], carrera: 'CONTADURIA' },
    { id: 'CPA-0440', sem: 7, nom: 'Auditoría Forense', pre: ['CPA-0400'], carrera: 'CONTADURIA' },
    { id: 'CPA-0410', sem: 7, nom: 'Auditoría II', pre: ['CPA-0400'], carrera: 'CONTADURIA' },
    { id: 'CPA-0430', sem: 7, nom: 'Auditoría Ambiental', pre: ['CPA-0400'], carrera: 'CONTADURIA' },
    
    { id: 'ELE-0300', sem: 8, nom: 'Electiva 3', pre: [], carrera: 'CONTADURIA', tipo: 'electiva' },
    { id: 'IND-0400', sem: 8, nom: 'Preparación y Evalación de Proyectos I', pre: ['ADM-0310'], carrera: 'CONTADURIA' },
    { id: 'CPA-0470', sem: 8, nom: 'Auditoría Tributaria y Fiscal', pre: ['CPA-0465'], carrera: 'CONTADURIA' },
    { id: 'CPA-0460', sem: 8, nom: 'Auditoría Gubernamental', pre: ['CPA-0410'], carrera: 'CONTADURIA' },
    { id: 'CPA-0455', sem: 8, nom: 'Auditoría Operativa', pre: ['CPA-0410'], carrera: 'CONTADURIA' },
    { id: 'CPA-0490', sem: 8, nom: 'Gabinete de Auditoria', pre: ['CPA-0410'], carrera: 'CONTADURIA' },

    // ==========================================
    // 4. INGENIERÍA EN GESTIÓN PETROLERA
    // ==========================================
    { id: 'LIN-0110', sem: 1, nom: 'Deontología y Prosocialidad', pre: [], carrera: 'PETROLERA' },
    { id: 'MAT-0100', sem: 1, nom: 'Fundamentos de Matemáticas', pre: [], carrera: 'PETROLERA' },
    { id: 'INV-0100', sem: 1, nom: 'Técnicas de Investigación', pre: [], carrera: 'PETROLERA' },
    { id: 'FIS-0100', sem: 1, nom: 'Física I', pre: [], carrera: 'PETROLERA' },
    { id: 'LIN-0200', sem: 1, nom: 'Inglés I', pre: [], carrera: 'PETROLERA' },
    { id: 'QMC-0100', sem: 1, nom: 'Química General e Inorgánica', pre: [], carrera: 'PETROLERA' },
    
    { id: 'MAT-0120', sem: 2, nom: 'Cálculo I', pre: ['MAT-0100'], carrera: 'PETROLERA' },
    { id: 'MAT-0110', sem: 2, nom: 'Algebra Lineal', pre: ['MAT-0100'], carrera: 'PETROLERA' },
    { id: 'MAT-0200', sem: 2, nom: 'Estadistica Descriptiva', pre: ['INV-0100'], carrera: 'PETROLERA' },
    { id: 'FIS-0200', sem: 2, nom: 'Física II', pre: ['FIS-0100'], carrera: 'PETROLERA' },
    { id: 'SIS-0116', sem: 2, nom: 'Informática para Ingeniería', pre: ['LIN-0200'], carrera: 'PETROLERA' },
    { id: 'QMC-0200', sem: 2, nom: 'Química Orgánica', pre: ['QMC-0100'], carrera: 'PETROLERA' },
    
    { id: 'MAT-0121', sem: 3, nom: 'Cálculo II', pre: ['MAT-0120'], carrera: 'PETROLERA' },
    { id: 'ADM-0100', sem: 3, nom: 'Administración I', pre: ['LIN-0110'], carrera: 'PETROLERA' },
    { id: 'MAT-0210', sem: 3, nom: 'Estadistica Inferencial', pre: ['MAT-0200'], carrera: 'PETROLERA' },
    { id: 'FIS-0300', sem: 3, nom: 'Mecánica de Fluidos', pre: ['FIS-0200'], carrera: 'PETROLERA' },
    { id: 'PET-0115', sem: 3, nom: 'Resistencia de Materiales', pre: ['FIS-0200'], carrera: 'PETROLERA' },
    { id: 'QMC-0300', sem: 3, nom: 'Termodinámica', pre: ['QMC-0200'], carrera: 'PETROLERA' },
    
    { id: 'IND-0130', sem: 4, nom: 'Dibujo Industrial Computarizado', pre: ['MAT-0110'], carrera: 'PETROLERA' },
    { id: 'INV-0110', sem: 4, nom: 'Métodos y Técnicas de Investigación aplicada', pre: ['MAT-0210'], carrera: 'PETROLERA' },
    { id: 'MAT-0300', sem: 4, nom: 'Investigación Operativa I', pre: ['MAT-0210'], carrera: 'PETROLERA' },
    { id: 'PET-0105', sem: 4, nom: 'Geología Estructural', pre: ['PET-0115'], carrera: 'PETROLERA' },
    { id: 'PET-0300', sem: 4, nom: 'Elementos de Perforación de Pozos', pre: ['PET-0115'], carrera: 'PETROLERA' },
    { id: 'ECO-0100', sem: 4, nom: 'Introducción a la Economía', pre: [], carrera: 'PETROLERA' },
    
    { id: 'PET-0400', sem: 5, nom: 'Producción Petrolera I', pre: ['IND-0130'], carrera: 'PETROLERA' },
    { id: 'PET-0310', sem: 5, nom: 'Fluidos de Perforación e Intervencipon de Pozos', pre: ['FIS-0300'], carrera: 'PETROLERA' },
    { id: 'PET-0200', sem: 5, nom: 'Reservorios I', pre: ['PET-0105'], carrera: 'PETROLERA' },
    { id: 'PET-0110', sem: 5, nom: 'Geología del Petróleo', pre: ['PET-0105'], carrera: 'PETROLERA' },
    { id: 'ECO-0235', sem: 5, nom: 'Ingeniería Económica', pre: ['ECO-0100'], carrera: 'PETROLERA' },
    { id: 'PET-0270', sem: 5, nom: 'Cadena de Valor del Gas Natural', pre: ['ECO-0100'], carrera: 'PETROLERA' },
    
    { id: 'PET-0402', sem: 6, nom: 'Producción Petrolera II', pre: ['PET-0400'], carrera: 'PETROLERA' },
    { id: 'PET-0120', sem: 6, nom: 'Petrofísica y Registro de Pozos', pre: ['PET-0400'], carrera: 'PETROLERA' },
    { id: 'PET-0320', sem: 6, nom: 'Ingeniería de Perforación de Pozos', pre: ['PET-0310'], carrera: 'PETROLERA' },
    { id: 'PET-0210', sem: 6, nom: 'Reservorios II', pre: ['PET-0200'], carrera: 'PETROLERA' },
    { id: 'PET-0330', sem: 6, nom: 'Cementación de Pozos', pre: ['PET-0300'], carrera: 'PETROLERA' },
    { id: 'PET-0280', sem: 6, nom: 'Tecnología del Gas Natural', pre: ['PET-0270'], carrera: 'PETROLERA' },
    
    { id: 'PET-0420', sem: 7, nom: 'Sistemas Artificiales de Producción', pre: ['PET-0402'], carrera: 'PETROLERA' },
    { id: 'MAB-0100', sem: 7, nom: 'Medio Ambiente y Desarrollo Sostenible', pre: ['PET-0400'], carrera: 'PETROLERA' },
    { id: 'PET-0340', sem: 7, nom: 'Técnicas de Perforación de Pozos', pre: ['PET-0320'], carrera: 'PETROLERA' },
    { id: 'PET-0220', sem: 7, nom: 'Caracterización Estatica de Yacimientos', pre: ['PET-0210'], carrera: 'PETROLERA' },
    { id: 'ADM-0420', sem: 7, nom: 'Emprendedurismo', pre: ['ECO-0235'], carrera: 'PETROLERA' },
    { id: 'PET-0290', sem: 7, nom: 'Transporte y Almacenaje de Hidrocarburos', pre: ['IGP606'], carrera: 'PETROLERA' },
    
    { id: 'PET-0430', sem: 8, nom: 'Conducción y Manejo de la Producción de Hidrocarburos', pre: ['PET-0420'], carrera: 'PETROLERA' },
    { id: 'IND-0320', sem: 8, nom: 'Seguridad e Higiene Ocupacional', pre: ['MAB-0100'], carrera: 'PETROLERA' },
    { id: 'DER-0255', sem: 8, nom: 'Derecho Minero e Hidrocarburifero', pre: ['MAB-0100'], carrera: 'PETROLERA' },
    { id: 'PET-0240', sem: 8, nom: 'Ingeniería de Yacimientos de Gas', pre: ['PET-0220'], carrera: 'PETROLERA' },
    { id: 'PET-0440', sem: 8, nom: 'Planificación y Administración de Proyectos Petroleros', pre: ['ADM-0420'], carrera: 'PETROLERA' },
    { id: 'ELE-0100', sem: 8, nom: 'Electiva 1', pre: [], carrera: 'PETROLERA', tipo: 'electiva' },
    
    { id: 'PET-0350', sem: 9, nom: 'Intervención y Mantenimiento de Pozos', pre: ['PET-0430'], carrera: 'PETROLERA' },
    { id: 'PET-0250', sem: 9, nom: 'Simulación Matemática de Yacimientos', pre: ['PET-0420'], carrera: 'PETROLERA' },
    { id: 'PET-0470', sem: 9, nom: 'Medio Ambiente en la Industria Petrolera', pre: ['MAB-0100'], carrera: 'PETROLERA' },
    { id: 'ELE-0200', sem: 9, nom: 'Electiva 2', pre: [], carrera: 'PETROLERA', tipo: 'electiva' },
    { id: 'PET-0450', sem: 9, nom: 'Evaluación de Proyectos Petroleros', pre: ['PET-0440'], carrera: 'PETROLERA' },
    { id: 'PET-0460', sem: 9, nom: 'Desarrollo del Mercado de Hidrocarburos', pre: ['PET-0290'], carrera: 'PETROLERA' },

    // ==========================================
    // 5. INGENIERÍA INDUSTRIAL
    // ==========================================
    { id: 'LIN-0110', sem: 1, nom: 'Deontología y Prosocialidad', pre: [], carrera: 'INDUSTRIAL' },
    { id: 'MAT-0100', sem: 1, nom: 'Fundamentos de Matemáticas', pre: [], carrera: 'INDUSTRIAL' },
    { id: 'INV-0100', sem: 1, nom: 'Técnicas de Investigación', pre: [], carrera: 'INDUSTRIAL' },
    { id: 'FIS-0100', sem: 1, nom: 'Física I', pre: [], carrera: 'INDUSTRIAL' },
    { id: 'ECO-0100', sem: 1, nom: 'Introducción a la Economía', pre: [], carrera: 'INDUSTRIAL' },
    { id: 'QMC-0100', sem: 1, nom: 'Química General e Inorgánica', pre: [], carrera: 'INDUSTRIAL' },
   
    { id: 'MAT-0120', sem: 2, nom: 'Cálculo I', pre: ['MAT-0100'], carrera: 'INDUSTRIAL' },
    { id: 'MAT-0110', sem: 2, nom: 'Algebra Lineal', pre: ['MAT-0100'], carrera: 'INDUSTRIAL' },
    { id: 'MAT-0200', sem: 2, nom: 'Estadística Descriptiva', pre: ['INV-0100'], carrera: 'INDUSTRIAL' },
    { id: 'FIS-0200', sem: 2, nom: 'Física II', pre: ['FIS-0100'], carrera: 'INDUSTRIAL' },
    { id: 'CPA-0100', sem: 2, nom: 'Contabilidad Empresarial I', pre: ['ECO-0100'], carrera: 'INDUSTRIAL' },
    { id: 'QMC-0200', sem: 2, nom: 'Química Organíca', pre: ['QMC-0100'], carrera: 'INDUSTRIAL' },
    
    { id: 'MAT-0121', sem: 3, nom: 'Cálculo II', pre: ['MAT-0120'], carrera: 'INDUSTRIAL' },
    { id: 'IND-0130', sem: 3, nom: 'Dibujo Industrial Computarizado', pre: ['MAT-0110'], carrera: 'INDUSTRIAL' },
    { id: 'MAT-0210', sem: 3, nom: 'Estadística Inferencial', pre: ['MAT-0200'], carrera: 'INDUSTRIAL' },
    { id: 'FIS-0400', sem: 3, nom: 'Electrotecnia Industrial', pre: ['FIS-0200'], carrera: 'INDUSTRIAL' },
    { id: 'CPA-0200', sem: 3, nom: 'Contabilidad de Costos I', pre: ['CPA-0100'], carrera: 'INDUSTRIAL' },
    { id: 'ADM-0100', sem: 3, nom: 'Administración I', pre: [], carrera: 'INDUSTRIAL' },
    
    { id: 'SIS-0328', sem: 4, nom: 'Programación numérica y Aplicaciones', pre: ['MAT-0121'], carrera: 'INDUSTRIAL' },
    { id: 'IND-0300', sem: 4, nom: 'Gestión de la Calidad I', pre: ['MAT-0200'], carrera: 'INDUSTRIAL' },
    { id: 'ADM-0200', sem: 4, nom: 'Investigación de Mercado I', pre: ['MAT-0200'], carrera: 'INDUSTRIAL' },
    { id: 'MAT-0300', sem: 4, nom: 'Investigación Operativa I', pre: ['MAT-0210'], carrera: 'INDUSTRIAL' },
    { id: 'FIS-0300', sem: 4, nom: 'Mecánica de Fluidos', pre: ['FIS-0200'], carrera: 'INDUSTRIAL' },
    { id: 'IND-0100', sem: 4, nom: 'Producción y Manufactura Flexible I', pre: ['ADM-0100'], carrera: 'INDUSTRIAL' },
    
    { id: 'IND-0120', sem: 5, nom: 'Ingeniería de Métodos y Ergonomía', pre: ['IND-0300'], carrera: 'INDUSTRIAL' },
    { id: 'INV-0110', sem: 5, nom: 'Métodos y Técnicas de Investigación Aplicada', pre: ['INV-0110'], carrera: 'INDUSTRIAL' },
    { id: 'PII503', sem: 5, nom: 'Construcciones e Instalaciones Industriales', pre: ['PII304'], carrera: 'INDUSTRIAL' },
    { id: 'PII504', sem: 5, nom: 'Temodinámica', pre: ['PII405'], carrera: 'INDUSTRIAL' },
    { id: 'PII505', sem: 5, nom: 'Operaciones Unitarias I', pre: ['PII406'], carrera: 'INDUSTRIAL' },
    { id: 'PII506', sem: 5, nom: 'Producción y Manufactura Flexible II', pre: ['PII406'], carrera: 'INDUSTRIAL' },
    
    { id: 'PII601', sem: 6, nom: 'Medio Ambiente y Desarrollo Sostenible', pre: [], carrera: 'INDUSTRIAL' },
    { id: 'PII602', sem: 6, nom: 'Gestión de la Calidad II', pre: ['PII402'], carrera: 'INDUSTRIAL' },
    { id: 'PII603', sem: 6, nom: 'Investigación Operativa II', pre: ['PII404'], carrera: 'INDUSTRIAL' },
    { id: 'PII604', sem: 6, nom: 'Ingeniería Económica', pre: ['PII305'], carrera: 'INDUSTRIAL' },
    { id: 'PII605', sem: 6, nom: 'Operaciones Unitarias I', pre: ['PII505'], carrera: 'INDUSTRIAL' },
    { id: 'PII606', sem: 6, nom: 'Procesos Industriales I', pre: ['PII505'], carrera: 'INDUSTRIAL' },
    
    { id: 'PII701', sem: 7, nom: 'Gestión del Mantenimiento', pre: ['PII503'], carrera: 'INDUSTRIAL' },
    { id: 'PII702', sem: 7, nom: 'Circuitos Eléctricos y Digitales', pre: ['PII401'], carrera: 'INDUSTRIAL' },
    { id: 'PII703', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'INDUSTRIAL', tipo: 'electiva' },
    { id: 'PII704', sem: 7, nom: 'Emprendedurismo', pre: ['PII604'], carrera: 'INDUSTRIAL' },
    { id: 'PII705', sem: 7, nom: 'Comportamiento Organizacional', pre: ['PII506'], carrera: 'INDUSTRIAL' },
    { id: 'PII706', sem: 7, nom: 'Procesos Industriales II', pre: ['PII606'], carrera: 'INDUSTRIAL' },
    
    { id: 'PII801', sem: 8, nom: 'Seguridad e Higiene Ocupacional', pre: ['PII701'], carrera: 'INDUSTRIAL' },
    { id: 'PII802', sem: 8, nom: 'Producción Limpia', pre: ['PII601'], carrera: 'INDUSTRIAL' },
    { id: 'PII803', sem: 8, nom: 'Automatización Industrial', pre: ['PII702'], carrera: 'INDUSTRIAL' },
    { id: 'PII804', sem: 8, nom: 'Neumática Aplicada', pre: ['PII702'], carrera: 'INDUSTRIAL' },
    { id: 'PII805', sem: 8, nom: 'Preparación y Evaluación de Proyectos I', pre: ['PII704'], carrera: 'INDUSTRIAL' },
    { id: 'PII806', sem: 8, nom: 'Gestión de Recursos Humanos', pre: ['PII705'], carrera: 'INDUSTRIAL' },
    
    { id: 'PII901', sem: 9, nom: 'Electiva 2', pre: [], carrera: 'INDUSTRIAL', tipo: 'electiva' },
    { id: 'PII902', sem: 9, nom: 'Electiva 3', pre: [], carrera: 'INDUSTRIAL', tipo: 'electiva' },
    { id: 'PII903', sem: 9, nom: 'Electiva 4', pre: [], carrera: 'INDUSTRIAL', tipo: 'electiva' },
    { id: 'PII904', sem: 9, nom: 'Robótica', pre: ['PII804'], carrera: 'INDUSTRIAL' },
    { id: 'PII905', sem: 9, nom: 'Preparación y Evaluación de Proyectos II', pre: ['PII805'], carrera: 'INDUSTRIAL' },
    { id: 'PII906', sem: 9, nom: 'Gerencia Estrategia Empresarial', pre: ['PII806'], carrera: 'INDUSTRIAL' },

    // ==========================================
    // ==========================================
    //        SECCIÓN 2: PLANES NUEVOS 2025
    // ==========================================
    // ==========================================

    // CARRERA: ADMINISTRACIÓN DE EMPRESAS (2025) - 8 Semestres
    { id: 'LIN-1100', sem: 1, nom: 'Metodología de la Investigación', pre: [], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'LIN-1110', sem: 1, nom: 'Ética y Ciudadanía Global', pre: [], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ADM-1100', sem: 1, nom: 'Administración I', pre: [], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'CPA-1100', sem: 1, nom: 'Contabilidad Empresarial I', pre: [], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ECO-1100', sem: 1, nom: 'Introducción a la Economía', pre: [], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ADM-1250', sem: 1, nom: 'Liderazgo y Comunicación Efectiva', pre: [], carrera: 'ADMINISTRACION_NUEVA' },

    { id: 'ADM-1110', sem: 2, nom: 'Administración II', pre: ['ADM-1100'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'MAT-1210', sem: 2, nom: 'Estadística Descriptiva', pre: ['LIN-1100'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'MAT-1105', sem: 2, nom: 'Matemática Aplicada', pre: ['LIN-1100'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ECO-1110', sem: 2, nom: 'Microeconomía I', pre: ['ECO-1100'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'CPA-1110', sem: 2, nom: 'Contabilidad Empresarial II', pre: ['CPA-1100'], carrera: 'ADMINISTRACION_NUEVA' },

    { id: 'INV-1210', sem: 3, nom: 'Investigación de Mercados I', pre: ['LIN-1100'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'INV-1230', sem: 3, nom: 'Análisis de Datos Estratégicos', pre: ['MAT-1210'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'MAT-1220', sem: 3, nom: 'Estadística Inferencial', pre: ['MAT-1210'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'MAT-1110', sem: 3, nom: 'Cálculo I', pre: ['MAT-1105'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ECO-1200', sem: 3, nom: 'Macroeconomía', pre: ['ECO-1100'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'CPA-1200', sem: 3, nom: 'Contabilidad de Costos I', pre: ['CPA-1110'], carrera: 'ADMINISTRACION_NUEVA' },

    { id: 'INV-1220', sem: 4, nom: 'Investigación de Mercados II', pre: ['INV-1210'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ADM-1140', sem: 4, nom: 'Gestión del Talento Humano I', pre: ['ADM-1110'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ADM-1130', sem: 4, nom: 'Diseño Organizacional', pre: ['ADM-1110'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'MKT-1100', sem: 4, nom: 'Fundamentos de Marketing', pre: ['INV-1210'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'DER-1210', sem: 4, nom: 'Derecho Societario', pre: [], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'FIN-1100', sem: 4, nom: 'Matemática Financiera', pre: ['MAT-1105'], carrera: 'ADMINISTRACION_NUEVA' },

    { id: 'ADM-1410', sem: 5, nom: 'Responsabilidad Social Empresarial', pre: [], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ADM-1150', sem: 5, nom: 'Gestión del Talento Humano II', pre: ['ADM-1140'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ADM-1350', sem: 5, nom: 'Desarrollo Organizacional', pre: ['ADM-1130'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'MKT-1240', sem: 5, nom: 'Marketing Estratégico', pre: ['MKT-1100'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'CPA-1310', sem: 5, nom: 'Tributación Aplicada I', pre: ['CPA-1100'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'FIN-1130', sem: 5, nom: 'Finanzas Corporativas I', pre: ['FIN-1100'], carrera: 'ADMINISTRACION_NUEVA' },

    { id: 'DER-1560', sem: 6, nom: 'Negociación y Resolución de Conflictos', pre: [], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'DER-1250', sem: 6, nom: 'Derecho Laboral y Seguridad Social', pre: ['ADM-1140'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ADM-1160', sem: 6, nom: 'Gestión de la Diversidad', pre: ['ADM-1150'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'IND-1450', sem: 6, nom: 'Gestión de la Calidad', pre: [], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'CPA-1140', sem: 6, nom: 'Presupuesto y Planificación', pre: ['FIN-1130'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'FIN-1140', sem: 6, nom: 'Finanzas Corporativas II', pre: ['FIN-1130'], carrera: 'ADMINISTRACION_NUEVA' },

    { id: 'ADM-1420', sem: 7, nom: 'Emprendedurismo e Innovación', pre: ['CPA-1140'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ELE-1100', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'ADMINISTRACION_NUEVA', tipo: 'electiva' },
    { id: 'ADM-1360', sem: 7, nom: 'Gerencia Estratégica', pre: ['ADM-1350'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ADM-1510', sem: 7, nom: 'Administración Pública I', pre: ['ADM-1100'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ELE-1200', sem: 7, nom: 'Electiva 2', pre: [], carrera: 'ADMINISTRACION_NUEVA', tipo: 'electiva' },
    { id: 'FIN-1220', sem: 7, nom: 'Mercado de Valores e Instrumentos Financieros', pre: ['FIN-1140'], carrera: 'ADMINISTRACION_NUEVA' },

    { id: 'ADM-1430', sem: 8, nom: 'Gestión de Incubación de Startups', pre: ['ADM-1420'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'SIS-1380', sem: 8, nom: 'Inteligencia de Negocios', pre: ['INV-1230'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'IND-1140', sem: 8, nom: 'Gerencia de Operaciones', pre: ['IND-1450'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ADM-1520', sem: 8, nom: 'Administración Pública II', pre: ['ADM-1510'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'ELE-1300', sem: 8, nom: 'Electiva 3', pre: [], carrera: 'ADMINISTRACION_NUEVA', tipo: 'electiva' },
    { id: 'IND-1400', sem: 8, nom: 'Preparación y Evaluación de Proyectos', pre: ['CPA-1140'], carrera: 'ADMINISTRACION_NUEVA' },
    { id: 'IND-1405', sem: 8, nom: 'Gerencia de Proyectos', pre: ['IND-1400'], carrera: 'ADMINISTRACION_NUEVA' },

    // CARRERA: INGENIERÍA DE SISTEMAS (2025) - 9 Semestres
    { id: 'LIN-1100', sem: 1, nom: 'Metodología de la Investigación', pre: [], carrera: 'SISTEMAS_NUEVA' },
    { id: 'MAT-1100', sem: 1, nom: 'Fundamentos de Matemáticas', pre: [], carrera: 'SISTEMAS_NUEVA' },
    { id: 'LIN-1200', sem: 1, nom: 'Inglés Técnico I', pre: [], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1120', sem: 1, nom: 'Programación Básica', pre: [], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1100', sem: 1, nom: 'Hardware, Software y Redes', pre: [], carrera: 'SISTEMAS_NUEVA' },
    { id: 'MAT-1150', sem: 1, nom: 'Estructuras Discretas', pre: [], carrera: 'SISTEMAS_NUEVA' },
    { id: 'MAT-1130', sem: 2, nom: 'Álgebra Lineal', pre: ['MAT-1100'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'MAT-1110', sem: 2, nom: 'Cálculo I', pre: ['MAT-1100'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'FIS-1100', sem: 2, nom: 'Física I', pre: ['MAT-1100'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1121', sem: 2, nom: 'Programación I', pre: ['SIS-1120'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1220', sem: 2, nom: 'Sistemas Operativos I', pre: ['SIS-1100'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'LIN-1110', sem: 2, nom: 'Ética y Ciudadanía Global', pre: [], carrera: 'SISTEMAS_NUEVA' },
    { id: 'MAT-1210', sem: 3, nom: 'Estadística Descriptiva', pre: ['MAT-1100'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'MAT-1120', sem: 3, nom: 'Cálculo II', pre: ['MAT-1110'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1400', sem: 3, nom: 'Gestión Financiera para TIC', pre: ['MAT-1110'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1122', sem: 3, nom: 'Programación II', pre: ['SIS-1121'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1221', sem: 3, nom: 'Sistemas Operativos II', pre: ['SIS-1220'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1130', sem: 3, nom: 'Sistemas Digitales I', pre: ['SIS-1100'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'IND-1210', sem: 4, nom: 'Investigación Operativa I', pre: ['MAT-1210'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'RED-1110', sem: 4, nom: 'Redes I', pre: ['SIS-1100'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'MAT-1240', sem: 4, nom: 'Análisis Numérico', pre: ['MAT-1120'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1123', sem: 4, nom: 'Programación III', pre: ['SIS-1122'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1125', sem: 4, nom: 'Base de Datos I', pre: ['MAT-1150'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1140', sem: 4, nom: 'Teoría de la Computación', pre: ['MAT-1150'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'MAT-1220', sem: 5, nom: 'Estadística Inferencial', pre: ['MAT-1210'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'RED-1120', sem: 5, nom: 'Redes II', pre: ['RED-1110'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1124', sem: 5, nom: 'Estructuras de Datos', pre: ['SIS-1123'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1300', sem: 5, nom: 'Desarrollo de Sistemas I', pre: ['SIS-1125'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1126', sem: 5, nom: 'Base de Datos II', pre: ['SIS-1125'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1310', sem: 5, nom: 'Sistemas de Información I', pre: ['SIS-1125'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1370', sem: 6, nom: 'Machine Learning', pre: ['MAT-1220'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1380', sem: 6, nom: 'Inteligencia de Negocios', pre: ['MAT-1220'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1330', sem: 6, nom: 'Desarrollo Web I', pre: ['SIS-1123'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1301', sem: 6, nom: 'Desarrollo de Sistemas II', pre: ['SIS-1300'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1127', sem: 6, nom: 'Administración de Base de Datos', pre: ['SIS-1126'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1311', sem: 6, nom: 'Sistemas de Información II', pre: ['SIS-1310'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1371', sem: 7, nom: 'Deep Learning', pre: ['SIS-1370'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'ADM-1420', sem: 7, nom: 'Emprendedurismo e Innovación', pre: ['SIS-1400'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1410', sem: 7, nom: 'Auditoría de Sistemas', pre: ['SIS-1311'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'RED-1300', sem: 7, nom: 'Administración de Servidores', pre: ['RED-1120'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1340', sem: 7, nom: 'Aplicaciones Móviles', pre: ['SIS-1330'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1420', sem: 7, nom: 'Gerenciamiento TIC', pre: ['SIS-1311'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1430', sem: 8, nom: 'Seguridad Informática', pre: ['RED-1300'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1331', sem: 8, nom: 'Desarrollo Web II', pre: ['SIS-1330'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1425', sem: 8, nom: 'Dirección de Proyectos', pre: ['SIS-1420'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'RED-1310', sem: 8, nom: 'Servicios de Infraestructura Nube', pre: ['RED-1300'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1128', sem: 8, nom: 'Tecnología de Base de Datos', pre: ['SIS-1127'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'ELE-1100', sem: 8, nom: 'Electiva 1', pre: [], carrera: 'SISTEMAS_NUEVA', tipo: 'electiva' },
    { id: 'SIS-1372', sem: 9, nom: 'Visión Computacional', pre: ['SIS-1371'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'RED-1220', sem: 9, nom: 'Internet de las Cosas', pre: ['RED-1120'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1305', sem: 9, nom: 'Calidad de Software', pre: ['SIS-1301'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1360', sem: 9, nom: 'DevOps', pre: ['RED-1310'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'SIS-1350', sem: 9, nom: 'Negocios Electrónicos', pre: ['SIS-1330'], carrera: 'SISTEMAS_NUEVA' },
    { id: 'ELE-1200', sem: 9, nom: 'Electiva 2', pre: [], carrera: 'SISTEMAS_NUEVA', tipo: 'electiva' },

    // CARRERA: INGENIERÍA INDUSTRIAL (2025) - 9 Semestres
    { id: 'MAT-1100', sem: 1, nom: 'Fundamentos de Matemáticas', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'LIN-1100', sem: 1, nom: 'Metodología de la Investigación', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'QMC-1100', sem: 1, nom: 'Química General', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'SIS-1120', sem: 1, nom: 'Programación Básica', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'FIS-1100', sem: 1, nom: 'Física I', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'LIN-1200', sem: 1, nom: 'Inglés Técnico I', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'MAT-1110', sem: 2, nom: 'Cálculo I', pre: ['MAT-1100'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'MAT-1130', sem: 2, nom: 'Álgebra Lineal', pre: ['MAT-1100'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'QMC-1110', sem: 2, nom: 'Química Orgánica', pre: ['QMC-1100'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'MAT-1210', sem: 2, nom: 'Estadística Descriptiva', pre: ['LIN-1100'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'FIS-1200', sem: 2, nom: 'Física II', pre: ['FIS-1100'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'LIN-1110', sem: 2, nom: 'Ética y Ciudadanía Global', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'MAT-1120', sem: 3, nom: 'Cálculo II', pre: ['MAT-1110'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1100', sem: 3, nom: 'Producción y Manufactura Flexible I', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1330', sem: 3, nom: 'Dibujo Computarizado', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'MAT-1220', sem: 3, nom: 'Estadística Inferencial', pre: ['MAT-1210'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'FIS-1300', sem: 3, nom: 'Dinámica de Fluidos', pre: ['FIS-1200'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'CPA-1100', sem: 3, nom: 'Contabilidad Empresarial I', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1210', sem: 4, nom: 'Investigación Operativa I', pre: ['MAT-1120'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1260', sem: 4, nom: 'Gestión de Datos', pre: ['MAT-1220'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1250', sem: 4, nom: 'Control Estadístico de Calidad', pre: ['MAT-1220'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'FIS-1400', sem: 4, nom: 'Electrotecnia Industrial', pre: ['FIS-1200'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'FIS-1310', sem: 4, nom: 'Termodinámica', pre: ['FIS-1200'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'ECO-1100', sem: 4, nom: 'Introducción a la Economía', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1220', sem: 5, nom: 'Investigación Operativa II', pre: ['IND-1210'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1101', sem: 5, nom: 'Producción y Manufactura Flexible II', pre: ['IND-1100'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1240', sem: 5, nom: 'Construcciones e Instalaciones Industriales', pre: ['IND-1330'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1230', sem: 5, nom: 'Ingeniería de Métodos', pre: ['MAT-1220'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1130', sem: 5, nom: 'Operaciones Unitarias I', pre: ['FIS-1300'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'CPA-1200', sem: 5, nom: 'Contabilidad de Costos I', pre: ['CPA-1100'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1350', sem: 6, nom: 'IA para la Innovación', pre: ['IND-1260'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1450', sem: 6, nom: 'Gestión de la Calidad', pre: ['IND-1250'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1340', sem: 6, nom: 'Gestión del Mantenimiento', pre: ['IND-1101'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'INV-1210', sem: 6, nom: 'Investigación de Mercados I', pre: ['IND-1250'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1131', sem: 6, nom: 'Operaciones Unitarias II', pre: ['IND-1130'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'ADM-1210', sem: 6, nom: 'Gestión del Talento Humano', pre: [], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'MKT-1230', sem: 7, nom: 'Marketing Digital', pre: ['INV-1210'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1410', sem: 7, nom: 'Gestión de Cadena de Suministros', pre: ['IND-1220'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1420', sem: 7, nom: 'Circuitos Eléctricos y Digitales', pre: ['FIS-1400'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1110', sem: 7, nom: 'Procesos Industriales I', pre: ['IND-1131'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'FIN-1110', sem: 7, nom: 'Ingeniería Financiera', pre: ['CPA-1200'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'ELE-1100', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'INDUSTRIAL_NUEVA', tipo: 'electiva' },
    { id: 'IND-1435', sem: 8, nom: 'Automatización Industrial', pre: ['IND-1420'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1440', sem: 8, nom: 'Seguridad e Higiene Ocupacional', pre: ['ADM-1210'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'ADM-1420', sem: 8, nom: 'Emprendedurismo e Innovación', pre: ['FIN-1110'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1120', sem: 8, nom: 'Procesos Industriales II', pre: ['IND-1110'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1400', sem: 8, nom: 'Preparación y Evaluación de Proyectos', pre: ['FIN-1110'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'ELE-1200', sem: 8, nom: 'Electiva 2', pre: [], carrera: 'INDUSTRIAL_NUEVA', tipo: 'electiva' },
    { id: 'IND-1460', sem: 9, nom: 'IA y Robótica', pre: ['IND-1435'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1430', sem: 9, nom: 'Sistemas Neumáticos', pre: ['IND-1435'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1470', sem: 9, nom: 'Producción Limpia', pre: ['IND-1440'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'IND-1405', sem: 9, nom: 'Gerencia de Proyectos', pre: ['IND-1400'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'ADM-1500', sem: 9, nom: 'Gerencia Estratégica', pre: ['ADM-1420'], carrera: 'INDUSTRIAL_NUEVA' },
    { id: 'ELE-1300', sem: 9, nom: 'Electiva 3', pre: [], carrera: 'INDUSTRIAL_NUEVA', tipo: 'electiva' },

    // CARRERA: INGENIERÍA COMERCIAL SEMIPRESENCIAL (2025) - 8 Semestres
    { id: 'LIN-1100', sem: 1, nom: 'Metodología de la Investigación', pre: [], carrera: 'COMERCIAL_NUEVA' },
    { id: 'LIN-1110', sem: 1, nom: 'Ética y Ciudadanía Global', pre: [], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ADM-1100', sem: 1, nom: 'Administración I', pre: [], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ADM-1250', sem: 1, nom: 'Liderazgo y Comunicación Efectiva', pre: [], carrera: 'COMERCIAL_NUEVA' },
    { id: 'MAT-1105', sem: 1, nom: 'Matemática Aplicada', pre: [], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ECO-1100', sem: 1, nom: 'Introducción a la Economía', pre: [], carrera: 'COMERCIAL_NUEVA' },
    { id: 'CPA-1100', sem: 1, nom: 'Contabilidad Empresarial I', pre: [], carrera: 'COMERCIAL_NUEVA' },
    { id: 'INV-1210', sem: 2, nom: 'Investigación de Mercados I', pre: ['LIN-1100'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ADM-1110', sem: 2, nom: 'Administración II', pre: ['ADM-1100'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'MAT-1210', sem: 2, nom: 'Estadística Descriptiva', pre: ['LIN-1100'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'MAT-1110', sem: 2, nom: 'Cálculo I', pre: ['MAT-1105'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ECO-1110', sem: 2, nom: 'Microeconomía I', pre: ['ECO-1100'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'CPA-1110', sem: 2, nom: 'Contabilidad Empresarial II', pre: ['CPA-1100'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'INV-1220', sem: 3, nom: 'Investigación de Mercados II', pre: ['INV-1210'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'MKT-1100', sem: 3, nom: 'Fundamentos de Marketing', pre: ['INV-1210'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'MAT-1220', sem: 3, nom: 'Estadística Inferencial', pre: ['MAT-1210'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'INV-1230', sem: 3, nom: 'Análisis de Datos Estratégicos', pre: ['MAT-1210'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ECO-1200', sem: 3, nom: 'Macroeconomía', pre: ['ECO-1100'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'CPA-1200', sem: 3, nom: 'Contabilidad de Costos I', pre: ['CPA-1110'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ADM-1200', sem: 4, nom: 'Design Thinking', pre: ['MKT-1100'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'MKT-1240', sem: 4, nom: 'Marketing Estratégico', pre: ['MKT-1100'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ADM-1210', sem: 4, nom: 'Gestión del Talento Humano I', pre: ['ADM-1110'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'IND-1210', sem: 4, nom: 'Investigación Operativa I', pre: ['MAT-1220'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ECO-1210', sem: 4, nom: 'Econometría', pre: ['ECO-1200'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'FIN-1100', sem: 4, nom: 'Matemática Financiera', pre: ['MAT-1110'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ADM-1410', sem: 5, nom: 'Responsabilidad Social Empresarial', pre: [], carrera: 'COMERCIAL_NUEVA' },
    { id: 'MKT-1250', sem: 5, nom: 'Marketing Operativo', pre: ['MKT-1240'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'MKT-1340', sem: 5, nom: 'Marketing Internacional', pre: ['MKT-1240'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'DER-1210', sem: 5, nom: 'Derecho Societario', pre: [], carrera: 'COMERCIAL_NUEVA' },
    { id: 'INT-1330', sem: 5, nom: 'Comercio Internacional', pre: ['ECO-1200'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'FIN-1140', sem: 5, nom: 'Finanzas Corporativas I', pre: ['FIN-1100'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ADM-1420', sem: 6, nom: 'Emprendedurismo e Innovación', pre: ['ADM-1410'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'MKT-1230', sem: 6, nom: 'Marketing Digital', pre: ['MKT-1250'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'COM-1190', sem: 6, nom: 'Comunicación y Redacción Publicitaria', pre: ['MKT-1250'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'IND-1450', sem: 6, nom: 'Gestión de la Calidad', pre: [], carrera: 'COMERCIAL_NUEVA' },
    { id: 'IND-1410', sem: 6, nom: 'Gestión de Cadena de Suministros', pre: ['IND-1210'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'FIN-1141', sem: 6, nom: 'Finanzas Corporativas II', pre: ['FIN-1140'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ADM-1505', sem: 7, nom: 'Modelos de Negocios Sostenibles', pre: ['ADM-1420'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'MKT-1300', sem: 7, nom: 'Gerencia de Ventas', pre: ['MKT-1250'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ELE-1100', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'COMERCIAL_NUEVA', tipo: 'electiva' },
    { id: 'ADM-1500', sem: 7, nom: 'Gerencia Estratégica', pre: ['ADM-1210'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'FIN-1300', sem: 7, nom: 'Trading y Mercados Financieros Digitales', pre: ['FIN-1141'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'IND-1400', sem: 7, nom: 'Preparación y Evaluación de Proyectos', pre: ['ADM-1420'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ELE-1200', sem: 8, nom: 'Electiva 2', pre: [], carrera: 'COMERCIAL_NUEVA', tipo: 'electiva' },
    { id: 'ELE-1300', sem: 8, nom: 'Electiva 3', pre: [], carrera: 'COMERCIAL_NUEVA', tipo: 'electiva' },
    { id: 'SIS-1380', sem: 8, nom: 'Inteligencia de Negocios', pre: ['INV-1230'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'ADM-1515', sem: 8, nom: 'Simulación Empresarial', pre: ['ADM-1500'], carrera: 'COMERCIAL_NUEVA' },
    { id: 'IND-1405', sem: 8, nom: 'Gerencia de Proyectos', pre: ['IND-1400'], carrera: 'COMERCIAL_NUEVA' },

    // CARRERA: CONTADURÍA PÚBLICA (2025) - 8 Semestres
    { id: 'ADM-1100', sem: 1, nom: 'Administración I', pre: [], carrera: 'CONTADURIA_NUEVA' },
    { id: 'MAT-1105', sem: 1, nom: 'Matemática Aplicada', pre: [], carrera: 'CONTADURIA_NUEVA' },
    { id: 'LIN-1100', sem: 1, nom: 'Metodología de la Investigación', pre: [], carrera: 'CONTADURIA_NUEVA' },
    { id: 'ADM-1250', sem: 1, nom: 'Liderazgo y Comunicación Efectiva', pre: [], carrera: 'CONTADURIA_NUEVA' },
    { id: 'ECO-1100', sem: 1, nom: 'Introducción a la Economía', pre: [], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1100', sem: 1, nom: 'Contabilidad Empresarial I', pre: [], carrera: 'CONTADURIA_NUEVA' },
    { id: 'ADM-1110', sem: 2, nom: 'Administración II', pre: ['ADM-1100'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'MAT-1110', sem: 2, nom: 'Cálculo I', pre: ['MAT-1105'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'MAT-1210', sem: 2, nom: 'Estadística Descriptiva', pre: ['LIN-1100'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'LIN-1110', sem: 2, nom: 'Ética y Ciudadanía Global', pre: [], carrera: 'CONTADURIA_NUEVA' },
    { id: 'ECO-1110', sem: 2, nom: 'Microeconomía I', pre: ['ECO-1100'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1110', sem: 2, nom: 'Contabilidad Empresarial II', pre: ['CPA-1100'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'DER-1210', sem: 3, nom: 'Derecho Societario', pre: [], carrera: 'CONTADURIA_NUEVA' },
    { id: 'FIN-1100', sem: 3, nom: 'Matemática Financiera', pre: ['MAT-1110'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'MAT-1220', sem: 3, nom: 'Estadística Inferencial', pre: ['MAT-1210'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1160', sem: 3, nom: 'Informática Aplicada con IA', pre: [], carrera: 'CONTADURIA_NUEVA' },
    { id: 'ECO-1200', sem: 3, nom: 'Macroeconomía', pre: ['ECO-1100'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1120', sem: 3, nom: 'Contabilidad Empresarial III', pre: ['CPA-1110'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1310', sem: 4, nom: 'Tributación Aplicada I', pre: ['DER-1210'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'FIN-1140', sem: 4, nom: 'Finanzas Corporativas I', pre: ['FIN-1100'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1170', sem: 4, nom: 'Análisis de Datos con IA', pre: ['MAT-1220'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1200', sem: 4, nom: 'Contabilidad de Costos I', pre: ['CPA-1120'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1150', sem: 4, nom: 'Contabilidad Internacional', pre: ['CPA-1120'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1130', sem: 4, nom: 'Contabilidad Empresarial IV', pre: ['CPA-1120'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1320', sem: 5, nom: 'Tributación Aplicada II', pre: ['CPA-1310'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'FIN-1141', sem: 5, nom: 'Finanzas Corporativas II', pre: ['FIN-1140'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1210', sem: 5, nom: 'Contabilidad de Costos II', pre: ['CPA-1200'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1350', sem: 5, nom: 'Contabilidad de Sociedades', pre: ['DER-1210'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1530', sem: 5, nom: 'Contabilidad de Servicios', pre: ['CPA-1130'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1520', sem: 5, nom: 'Contabilidad Bancaria y de Seguros', pre: ['CPA-1130'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1140', sem: 6, nom: 'Presupuesto y Planificación', pre: ['FIN-1141'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1590', sem: 6, nom: 'Contabilidad Extractiva', pre: ['CPA-1210'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1370', sem: 6, nom: 'Contabilidad Agropecuaria', pre: ['CPA-1210'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1490', sem: 6, nom: 'Auditoría Financiera I', pre: ['CPA-1520'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1630', sem: 6, nom: 'Taller de Gestión Contable', pre: ['CPA-1350'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1600', sem: 6, nom: 'Contabilidad Integrada Gubernamental', pre: ['CPA-1130'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'IND-1400', sem: 7, nom: 'Preparación y Evaluación de Proyectos', pre: ['CPA-1140'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'ADM-1420', sem: 7, nom: 'Emprendedurismo e Innovación', pre: ['ADM-1250'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1510', sem: 7, nom: 'Auditoría Interna y Operativa', pre: ['CPA-1490'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1500', sem: 7, nom: 'Auditoría Financiera II', pre: ['CPA-1490'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1670', sem: 7, nom: 'Auditoría de Sistemas e Información', pre: ['CPA-1490'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'ELE-1100', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'CONTADURIA_NUEVA', tipo: 'electiva' },
    { id: 'CPA-1470', sem: 8, nom: 'Auditoría Tributaria y Fiscal', pre: ['CPA-1320'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1650', sem: 8, nom: 'Auditoría Forense', pre: ['CPA-1500'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1660', sem: 8, nom: 'Auditoría Ambiental', pre: ['CPA-1510'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1680', sem: 8, nom: 'Taller de Auditoría Financiera', pre: ['CPA-1500'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'CPA-1460', sem: 8, nom: 'Auditoría Gubernamental', pre: ['CPA-1600'], carrera: 'CONTADURIA_NUEVA' },
    { id: 'ELE-1200', sem: 8, nom: 'Electiva 2', pre: [], carrera: 'CONTADURIA_NUEVA', tipo: 'electiva' },

    // CARRERA: DERECHO (2025) - 8 Semestres
    { id: 'DER-1420', sem: 1, nom: 'Criminología y Ciencias Forenses', pre: [], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1100', sem: 1, nom: 'Derecho Civil I', pre: [], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1110', sem: 1, nom: 'Teoría General del Derecho', pre: [], carrera: 'DERECHO_NUEVA' },
    { id: 'LIN-1100', sem: 1, nom: 'Metodología de la Investigación', pre: [], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1560', sem: 1, nom: 'Oratoria Jurídica', pre: [], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1220', sem: 1, nom: 'Derechos Humanos', pre: [], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1610', sem: 2, nom: 'LegalTech I', pre: [], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1101', sem: 2, nom: 'Derecho Civil II', pre: ['DER-1100'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1410', sem: 2, nom: 'Psicología Jurídica', pre: ['DER-1420'], carrera: 'DERECHO_NUEVA' },
    { id: 'LIN-1110', sem: 2, nom: 'Ética y Ciudadanía Global', pre: [], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1570', sem: 2, nom: 'Interpretación y Argumentación Jurídica', pre: ['DER-1560'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1210', sem: 2, nom: 'Derecho Constitucional I', pre: ['DER-1110'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1620', sem: 3, nom: 'LegalTech II', pre: ['DER-1610'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1400', sem: 3, nom: 'Derecho Penal I', pre: ['DER-1420'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1102', sem: 3, nom: 'Derecho Civil III', pre: ['DER-1101'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1240', sem: 3, nom: 'Derecho Procesal y Orgánica Judicial', pre: ['DER-1110'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1580', sem: 3, nom: 'Redacción Jurídica', pre: ['DER-1570'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1211', sem: 3, nom: 'Derecho Constitucional II', pre: ['DER-1210'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1401', sem: 4, nom: 'Derecho Penal II', pre: ['DER-1400'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1103', sem: 4, nom: 'Derecho Civil IV', pre: ['DER-1102'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1260', sem: 4, nom: 'Derecho de las Familias', pre: ['DER-1101'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1241', sem: 4, nom: 'Derecho Administrativo', pre: ['DER-1211'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1550', sem: 4, nom: 'Técnicas de Investigación Jurídica', pre: ['LIN-1100'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1242', sem: 4, nom: 'Derecho Autonómico', pre: ['DER-1211'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1230', sem: 5, nom: 'Derecho Ecológico', pre: ['DER-1241'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1104', sem: 5, nom: 'Derecho Civil V', pre: ['DER-1103'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1330', sem: 5, nom: 'Derecho Societario', pre: ['DER-1102'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1335', sem: 5, nom: 'Derecho Tributario', pre: ['DER-1241'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1270', sem: 5, nom: 'Derecho Internacional Público', pre: ['DER-1220'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1250', sem: 5, nom: 'Derecho Laboral y Seguridad Social', pre: ['DER-1240'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1231', sem: 6, nom: 'Derecho Agroambiental', pre: ['DER-1230'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1530', sem: 6, nom: 'Derecho Notarial', pre: ['DER-1104'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1380', sem: 6, nom: 'Contratos Comerciales', pre: ['DER-1330'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1261', sem: 6, nom: 'Derecho de la Niñez y Adolescencia', pre: ['DER-1260'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1280', sem: 6, nom: 'Derecho Internacional Privado', pre: ['DER-1270'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1540', sem: 6, nom: 'Derecho Jurisprudencial', pre: ['DER-1211'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1430', sem: 7, nom: 'Derecho Procesal Penal', pre: ['DER-1401'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1310', sem: 7, nom: 'Derecho Procesal Civil', pre: ['DER-1104'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1315', sem: 7, nom: 'Derecho Procesal de Familia', pre: ['DER-1261'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1340', sem: 7, nom: 'Derecho Procesal Administrativo', pre: ['DER-1241'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1215', sem: 7, nom: 'Derecho Procesal Constitucional', pre: ['DER-1211'], carrera: 'DERECHO_NUEVA' },
    { id: 'ELE-1100', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'DERECHO_NUEVA', tipo: 'electiva' },
    { id: 'DER-1371', sem: 8, nom: 'Práctica Forense Penal', pre: ['DER-1430'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1370', sem: 8, nom: 'Práctica Forense Civil', pre: ['DER-1310'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1461', sem: 8, nom: 'Arbitraje y Conciliación', pre: ['DER-1380'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1460', sem: 8, nom: 'Justicia Restaurativa y Métodos Alternos', pre: ['DER-1430'], carrera: 'DERECHO_NUEVA' },
    { id: 'DER-1345', sem: 8, nom: 'Derecho Económico', pre: ['DER-1380'], carrera: 'DERECHO_NUEVA' },
    { id: 'ELE-1200', sem: 8, nom: 'Electiva 2', pre: [], carrera: 'DERECHO_NUEVA', tipo: 'electiva' },

    // CARRERA: INGENIERÍA EN REDES Y TELECOMUNICACIONES (2025) - 9 Semestres
    { id: 'LIN-1100', sem: 1, nom: 'Metodología de la Investigación', pre: [], carrera: 'REDES_NUEVA' },
    { id: 'MAT-1100', sem: 1, nom: 'Fundamentos de Matemáticas', pre: [], carrera: 'REDES_NUEVA' },
    { id: 'LIN-1200', sem: 1, nom: 'Inglés Técnico I', pre: [], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1120', sem: 1, nom: 'Programación Básica', pre: [], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1100', sem: 1, nom: 'Hardware, Software y Redes', pre: [], carrera: 'REDES_NUEVA' },
    { id: 'MAT-1150', sem: 1, nom: 'Estructuras Discretas', pre: [], carrera: 'REDES_NUEVA' },

    { id: 'MAT-1130', sem: 2, nom: 'Álgebra Lineal', pre: ['MAT-1100'], carrera: 'REDES_NUEVA' },
    { id: 'MAT-1110', sem: 2, nom: 'Cálculo I', pre: ['MAT-1100'], carrera: 'REDES_NUEVA' },
    { id: 'FIS-1100', sem: 2, nom: 'Física I', pre: ['MAT-1100'], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1121', sem: 2, nom: 'Programación I', pre: ['SIS-1120'], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1110', sem: 2, nom: 'Sistemas Digitales I', pre: ['MAT-1150'], carrera: 'REDES_NUEVA' },
    { id: 'LIN-1110', sem: 2, nom: 'Ética y Ciudadanía Global', pre: [], carrera: 'REDES_NUEVA' },

    { id: 'MAT-1210', sem: 3, nom: 'Estadística Descriptiva', pre: ['MAT-1100'], carrera: 'REDES_NUEVA' },
    { id: 'MAT-1120', sem: 3, nom: 'Cálculo II', pre: ['MAT-1110'], carrera: 'REDES_NUEVA' },
    { id: 'FIS-1200', sem: 2, nom: 'Física II', pre: ['FIS-1100'], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1122', sem: 3, nom: 'Programación II', pre: ['SIS-1121'], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1210', sem: 3, nom: 'Sistemas Operativos I', pre: ['SIS-1100'], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1111', sem: 3, nom: 'Sistemas Digitales II', pre: ['SIS-1110'], carrera: 'REDES_NUEVA' },

    { id: 'RED-1110', sem: 4, nom: 'Redes I', pre: ['SIS-1100'], carrera: 'REDES_NUEVA' },
    { id: 'TEL-1100', sem: 4, nom: 'Fundamentos de Telecomunicaciones', pre: ['FIS-1100'], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1125', sem: 4, nom: 'Base de Datos I', pre: ['MAT-1150'], carrera: 'REDES_NUEVA' },
    { id: 'FIS-1410', sem: 4, nom: 'Circuitos Eléctricos', pre: ['FIS-1200'], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1220', sem: 4, nom: 'Sistemas Operativos II', pre: ['SIS-1210'], carrera: 'REDES_NUEVA' },
    { id: 'TEL-1200', sem: 4, nom: 'Análisis de Señales y Sistemas', pre: ['MAT-1120'], carrera: 'REDES_NUEVA' },

    { id: 'RED-1120', sem: 5, nom: 'Redes II', pre: ['RED-1110'], carrera: 'REDES_NUEVA' },
    { id: 'RED-1210', sem: 5, nom: 'Diseño de Infraestructura de Redes Físicas', pre: ['RED-1110'], carrera: 'REDES_NUEVA' },
    { id: 'TEL-1110', sem: 5, nom: 'Sistemas de Comunicación I', pre: ['TEL-1100'], carrera: 'REDES_NUEVA' },
    { id: 'FIS-1420', sem: 5, nom: 'Electrónica Básica', pre: ['FIS-1410'], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1240', sem: 5, nom: 'Administración de Servidores', pre: ['SIS-1220'], carrera: 'REDES_NUEVA' },
    { id: 'TEL-1210', sem: 5, nom: 'Propagación y Antenas', pre: ['TEL-1100'], carrera: 'REDES_NUEVA' },

    { id: 'RED-1130', sem: 6, nom: 'Redes III', pre: ['RED-1120'], carrera: 'REDES_NUEVA' },
    { id: 'RED-1300', sem: 6, nom: 'Seguridad de Redes', pre: ['RED-1120'], carrera: 'REDES_NUEVA' },
    { id: 'TEL-1111', sem: 6, nom: 'Sistemas de Comunicación II', pre: ['TEL-1110'], carrera: 'REDES_NUEVA' },
    { id: 'FIS-1421', sem: 6, nom: 'Electrónica Digital y Microcontroladores', pre: ['FIS-1420'], carrera: 'REDES_NUEVA' },
    { id: 'RED-1310', sem: 6, nom: 'Servicios de Infraestructura Nube', pre: ['SIS-1240'], carrera: 'REDES_NUEVA' },
    { id: 'TEL-1220', sem: 6, nom: 'Microondas y Satélites', pre: ['TEL-1210'], carrera: 'REDES_NUEVA' },

    { id: 'RED-1140', sem: 7, nom: 'Redes IV', pre: ['RED-1130'], carrera: 'REDES_NUEVA' },
    { id: 'RED-1305', sem: 7, nom: 'Ciberseguridad Avanzada', pre: ['RED-1300'], carrera: 'REDES_NUEVA' },
    { id: 'TEL-1120', sem: 7, nom: 'Comunicaciones Ópticas', pre: ['TEL-1111'], carrera: 'REDES_NUEVA' },
    { id: 'RED-1220', sem: 7, nom: 'Internet de las Cosas', pre: ['RED-1120'], carrera: 'REDES_NUEVA' },
    { id: 'SIS-1420', sem: 7, nom: 'Gerenciamiento TIC', pre: ['RED-1130'], carrera: 'REDES_NUEVA' },
    { id: 'ELE-1100', sem: 7, nom: 'Electiva 1', pre: [], carrera: 'REDES_NUEVA', tipo: 'electiva' },

    { id: 'RED-1150', sem: 8, nom: 'Redes V', pre: ['RED-1140'], carrera: 'REDES_NUEVA' },
    { id: 'RED-1160', sem: 8, nom: 'Redes Definidas por Software', pre: ['RED-1140'], carrera: 'REDES_NUEVA' },
    { id: 'TEL-1300', sem: 8, nom: 'Comunicaciones Móviles e Inalámbricas', pre: ['TEL-1111'], carrera: 'REDES_NUEVA' },
    { id: 'ADM-1420', sem: 8, nom: 'Emprendedurismo e Innovación', pre: ['SIS-1420'], carrera: 'REDES_NUEVA' },
    { id: 'TEL-1310', sem: 8, nom: 'Telefonía IP', pre: ['RED-1140'], carrera: 'REDES_NUEVA' },
    { id: 'ELE-1200', sem: 8, nom: 'Electiva 2', pre: [], carrera: 'REDES_NUEVA', tipo: 'electiva' },

    { id: 'RED-1400', sem: 9, nom: 'Taller de Redes y Telecomunicaciones', pre: ['RED-1150'], carrera: 'REDES_NUEVA' },
    { id: 'TEL-1320', sem: 9, nom: 'Gestión de Redes de Telecomunicaciones', pre: ['TEL-1300'], carrera: 'REDES_NUEVA' },
    { id: 'RED-1410', sem: 9, nom: 'Auditoría de Redes y Seguridad', pre: ['RED-1305'], carrera: 'REDES_NUEVA' },
    { id: 'IND-1400', sem: 9, nom: 'Preparación y Evaluación de Proyectos', pre: ['ADM-1420'], carrera: 'REDES_NUEVA' },
    { id: 'ELE-1300', sem: 9, nom: 'Electiva 3', pre: [], carrera: 'REDES_NUEVA', tipo: 'electiva' },
    { id: 'ELE-1400', sem: 9, nom: 'Electiva 4', pre: [], carrera: 'REDES_NUEVA', tipo: 'electiva' },

];

// --- NUEVA SECCIÓN: LISTA BLANCA DE ELECTIVAS POR CARRERA ---
const ELECTIVAS_POR_CARRERA = {
    'DERECHO': [
        'PRACTICA FORENSE PENAL', 
        'PRACTICA FORENSE CIVIL', 
        'TECNICAS DE ORATORIA', 
        'DERECHO AUTONOMICO',
        'ARGUMENTACION JURIDICA'
    ],
    'DERECHO_NUEVA': [
        'DERECHO ADUANERO', 
        'DERECHO DE LA PROPIEDAD INTELECTUAL', 
        'DERECHO DEL DEPORTE', 
        'DERECHO MINERO E HIDORCARBUROS',
        'DERECHO PROCESAL LABORAL', 
        'LITIGIO ESTRATÉGICO CIVIL', 
        'LITIGIO ESTRATÉGICO CONSTITUCIONAL', 
        'LITIGIO ESTRATÉGICO EN LA JUSRISDICCIÓN ARBITRAL',
        'LITIGIO ESTRATÉGICO CONSTITUCIONAL',
        'LITIGIO ESTRATÉGICO CONSTITUCIONAL',
        'LITIGIO ESTRATÉGICO CONSTITUCIONAL',
        'LITIGIO ESTRATÉGICO CONSTITUCIONAL',
        'LITIGIO ESTRATÉGICO CONSTITUCIONAL' 
    ],
    'REDES': [
        'TELEFONIA IP', 
        'SEGURIDAD DE REDES', 
        'GESTION DE PROYECTOS TI',
        'VIRTUALIZACION'
    ],
    'REDES_NUEVA': [
        'CIBERSEGURIDAD AVANZADA',
        'FORENSE INFORMATICA',
        'ADMINISTRACION DE NUBE'
    ],
    'SISTEMAS': [
        'COMPUTACION EN LA NUBE',
        'REALIDAD VIRTUAL',
        'MINERIA DE DATOS'
    ],
    'SISTEMAS_NUEVA': [
        'BLOCKCHAIN',
        'INTERNET DE LAS COSAS',
        'GOBIERNO DE IT'
    ]
};

// LÓGICA DE FILTRADO FINAL ROBUSTA
const urlParamsFiltro = new URLSearchParams(window.location.search);
const carreraFiltrada = (urlParamsFiltro.get('carrera') || 'REDES').toUpperCase();

// Variable global que lee motor.js
var materias = todasLasMaterias.filter(m => m.carrera === carreraFiltrada);
